### ISSUE TITLE
Update Repository Metadata?

### ISSUE THREAD

**Issue by IanLee1521** [HPCToolkit/hpctoolkit#1]
Would it make sense to update the repository metadata? Currently it just says that it is "... exported from code.google.com ..." :

<img width="992" alt="screen shot 2016-10-09 at 20 08 13" src="https://cloud.githubusercontent.com/assets/828452/19226155/3c33ba1c-8e5c-11e6-8118-dd8ebaa3d639.png">

**Comment by jmellorcrummey** [comment]
done
