### ISSUE TITLE
hpcrun doesn't deliver samples for kernel 4.8 with frequency enabled

### ISSUE THREAD

**Issue by laksono** [HPCToolkit/hpctoolkit#105]
This only happens on Kernel 4.8 and Intel Broadwell (reported by Milind).

- Setting `HPCRUN_PRECISE_IP=0` produces samples with frequency "f" setting.
- The perf_event_open does not complain when hpcrun attempts to open it with `HPCRUN_PRECISE_IP>1.`
- Without frequency sampling, `HPCRUN_PRECISE_IP=3` delivers samples just fine.

Perhaps we should disable precise_ip by default, unless the user sets it.

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/105)
