### ISSUE TITLE
Support for 64-bit

### ISSUE THREAD

**Issue by twang15** [HPCToolkit/hpctoolkit#11]
http://hpctoolkit.org/software-instructions.html asks for building 32-bit binary on a 64-bit machine, with "gcc -m32" and "g++ -m32". Is this required or recommended? Is there any known issue for a 64-bit build?

**Comment by jmellorcrummey** [comment]
I apologize that this question has sat unattended for so long. We don't have automatic notifications set up when people log issues. I only noticed this when reviewing open issues.

We recommend that you use a 64-bit build on x86_64 using the default instructions under "Building and Installing" at http://hpctoolkit.org/software-instructions.html.  The 32-bit build of HPCToolkit was listed as a selected example in case someone needed this unusual configuration.
