### ISSUE TITLE
hpclink fails on ARM

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpctoolkit#115]
On ARM, uw_recipe_tostr lacks a definition, which causes hpclink to fail.

Since there are two kinds of unwind recipes, libunwind and those computed by our binary analyzer, we should a separate routine for printing unwind recipes of each kind. It looks like the code might need a  bit of restructuring to do that.

Below is the output from trying to build a static binary with hpclink in hpctoolkit-tests/applications/fib

[johnmc@arm1 fib]$ make fib-static
hpclink gcc -g -fopenmp -o fib fib.c
hpclink: preliminary link 1 ...
hpclink: unable to link

gcc -Wl,--wrap=dlclose -Wl,--wrap=dlopen -Wl,--wrap=execl -Wl,--wrap=execle -Wl,--wrap=execlp -Wl,--wrap=execv -Wl,--wrap=execve -Wl,--wrap=execvp -Wl,--wrap=fork -Wl,--wrap=system -Wl,--wrap=vfork -Wl,--wrap=sigaction -Wl,--wrap=signal -Wl,--wrap=sigprocmask -Wl,--wrap=MPI_Init -Wl,--wrap=MPI_Init_thread -Wl,--wrap=MPI_Finalize -Wl,--wrap=MPI_Comm_rank -Wl,--wrap=mpi_init -Wl,--wrap=mpi_init_thread -Wl,--wrap=mpi_finalize -Wl,--wrap=mpi_comm_rank -Wl,--wrap=mpi_init_ -Wl,--wrap=mpi_init_thread_ -Wl,--wrap=mpi_finalize_ -Wl,--wrap=mpi_comm_rank_ -Wl,--wrap=mpi_init__ -Wl,--wrap=mpi_init_thread__ -Wl,--wrap=mpi_finalize__ -Wl,--wrap=mpi_comm_rank__ -Wl,--wrap=_Exit -Wl,--wrap=_exit -Wl,--wrap=exit -Wl,--wrap=main -Wl,--wrap=pthread_create -Wl,--wrap=pthread_exit -Wl,--wrap=pthread_sigmask -Wl,--wrap=sigtimedwait -Wl,--wrap=sigwait -Wl,--wrap=sigwaitinfo /home/johnmc/pkgs-src/hpctoolkit/INSTALL/lib/hpctoolkit/libhpcrun.o /home/johnmc/pkgs-src/hpctoolkit/INSTALL/lib/hpctoolkit/ext-libs/liblzma.a -g -fopenmp -o fib fib.c _hpc_nm_addrs_20540.o /home/johnmc/pkgs-src/hpctoolkit/INSTALL/lib/hpctoolkit/libhpcrun_wrap.a /home/johnmc/pkgs-src/hpctoolkit/INSTALL/lib/hpctoolkit/ext-libs/libmonitor_wrap.a -ldl -lrt -lpthread

/home/johnmc/pkgs-src/hpctoolkit/INSTALL/lib/hpctoolkit/libhpcrun.o: In function `uwi_t_tostr':
(.text+0x226e8): undefined reference to `uw_recipe_tostr'
collect2: error: ld returned 1 exit status

hpclink: error: unable to link

**Comment by unkadoug** [comment]
Two changes fixed this problem:

commit 1ee17f7cec79cb9fda457d51024babf3e3b72d60
Author: Doug Moore <unkadoug@gmail.com>
Date:   Mon Oct 29 23:44:05 2018 -0500

    Fix sprintf -> snprinf typo.

commit ed3f16c6a5ca399a6a09275a6e9d9b807b79ff87
Author: Doug Moore <unkadoug@gmail.com>
Date:   Mon Oct 29 18:41:50 2018 -0500

    Define a recipe-printer for libunwind recipes that just prints "*".
    Use the libuwind recipe-printer for printing generic-unwind (like
    ARM) recipes.
