### ISSUE TITLE
hpcprof-mpi failed with Nekbone due to CCT node association with linux-vdso.so.1

### ISSUE THREAD

**Issue by laksono** [HPCToolkit/hpctoolkit#12]
@jmellorcrummey 
@mwkrentel 

hpcprof-mpi quits with an error message: 

"**failed to find structure for: S i="125626" s="0" l="0" strct="0" n="[assoc(NULL (0)) ip(2, 0x7ffe8d8acbce) lip()]" [../../../../src/lib/analysis/CallPath.cpp:450**]"

I believe the problem is due to association a CCT node with invalid load module: linux-vdso.so.1
It's unknown why a node can be associated with this load module.

Here's the complete output:

[la5@staff-65-dun20-126 example1]$ ~/pkgs/hpctoolkit-master/bin/hpcprof-mpi -S nekbone.hpcstruct -o hpctoolkit-master-nekbone-database hpctoolkit-master-nekbone-measurements/
msg: STRUCTURE: /home/la5/git/hpctoolkit-tests/applications/nekbone-2.3.4/test/example1/nekbone
msg: Line map : linux-vdso.so.1
msg: Line map : /home/la5/pkgs/hpctoolkit-master/lib/hpctoolkit/ext-libs/libmonitor.so.0.0.0
msg: Line map : /projects/pkgs/mpich-3.2/lib/libmpifort.so.12.1.0
msg: Line map : /projects/pkgs/mpich-3.2/lib/libmpi.so.12.1.0
msg: Line map : /usr/lib64/libgfortran.so.3.0.0
msg: Line map : /usr/lib64/libm-2.24.so
msg: Line map : /usr/lib64/libgomp.so.1.0.0
msg: Line map : /usr/lib64/libc-2.24.so
msg: Line map : /usr/lib64/libdl-2.24.so
msg: Line map : /usr/lib64/ld-2.24.so
ERROR: Cannot fully process samples because of errors reading load modules:
  'linux-vdso.so.1': No such file or directory

        [../../../../src/lib/analysis/CallPath.cpp:357]
ERROR: [Diagnostics::FatalException] Analysis::CallPath::noteStaticStructureOnLeaves: failed to find structure for: S i="125626" s="0" l="0" strct="0" n="[assoc(NULL (0)) ip(2, 0x7ffe8d8acbce) lip()]" [../../../../src/lib/analysis/CallPath.cpp:450]
        [../../../../src/tool/hpcprof-mpi/main.cpp:183]

**Comment by laksono** [comment]
If we comment the assertion:

 448       VMA lm_ip = n_dyn->lmIP();
 449       const Prof::Struct::ACodeNode* strct = lmStrct->findByVMA(lm_ip);
 450       **//DIAG_Assert**(strct, "Analysis::CallPath::noteStaticStructureOnLeaves: failed to find structure for: " << n_dyn->toStringMe(Prof::CCT::Tree::OFlg_DebugAll));

Another error message occurs:
ERROR: Cannot fully process samples because of errors reading load modules:
  'linux-vdso.so.1': No such file or directory

        [../../../../src/lib/analysis/CallPath.cpp:357]
ERROR: [Diagnostics::FatalException] CCT::ANode::mergeDeep: adding not permitted [../../../../src/lib/prof/CCT-Tree.cpp:813]
        [../../../../src/tool/hpcprof-mpi/main.cpp:183]

**Comment by jmellorcrummey** [comment]
fixed with new minimal vdso support completed in commit 5566357f62c492623e634d2f1918211c0d74a1f1
