### ISSUE TITLE
Need to handle samples in VDSO

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpctoolkit#121]
<img width="746" alt="image" src="https://user-images.githubusercontent.com/3926112/54481354-87adeb00-4801-11e9-8a65-2f8a31eee2c4.png">

**Comment by martyitz** [comment]
Isn't this fixed by now?

**Comment by jmellorcrummey** [comment]
this is fixed in master with the merge of the gpu branch and my recent unwinder fixes before the release.
