### ISSUE TITLE
TBB malloc proxy library makes Symtab non-deterministic

### ISSUE THREAD

**Issue by mwkrentel** [HPCToolkit/hpctoolkit#136]
I recently tracked down an odd form of non-determinism in hpcstruct.
Dyninst uses Intel TBB, which is fine.  But adding the Intel TBB
malloc proxy library triggers non-deterministic behavior in Symtab and
ParseAPI.

To recap, the TBB malloc proxy library provides wrappers for malloc()
and free(), etc, to make them use the TBB scalable malloc library.
You can insert the proxy library either by direct linking or with
LD_PRELOAD.  (I tried it both ways and it's non-det both ways.  I've
also tried the latest version 2019.4.)

https://www.threadingbuildingblocks.org/docs/help/tbb_userguide/Linux_C_Dynamic_Memory_Interface_Replacement.html

With the malloc proxy library, some of the non-determinism is
"benign".  Things like Symtab returning a list of mangled and pretty
names that are the same list, but in a different order.  (Hpcstruct
selects the maximum element by some order, so this, by itself is not
enough to produce a different struct file.)

Note: Symtab doesn't use threads, and I can produce the same non-det
behavior with openmp turned off.  So, it's not a thread data race.

This much is mostly harmless, but it does suggest that Symtab may be
producing an order based on its malloc() address rather than the
contents.

But some of the non-det is not so harmless.  I found a few
instructions where Symtab sometimes says some instruction is inlined
(has a getContainingFunction) and sometimes not.  I don't know if the
"harmless" non-det is triggering the inline difference, or if it's a
similar problem in a different place.

I guess one of three things must be true: (1) the TBB malloc library
is broken, where "broken" means that it's not as invisible as it
claims to be, (2) I'm not linking with the proxy library correctly
(I've tried both ways, both are non-det), or (3) something in Symtab
is not as deterministic as it should be, something like ordering based
on malloc address.

(1) and (2) are hard to believe.  But if the answer is (3), that must
mean that GNU glibc malloc is super deterministic and never produces
the conditions that show up the non-det in Symtab.  I'm skeptical.
Plus, this only happens on x86, not powerpc.

Also, even without the proxy library, I've seen some remaining
non-determinism in ParseAPI, at least on x86.  I've seen infrequent
cases where there's an indirect jmpq that sometimes has 16 outgoing
edges and sometimes 38 edges.

Anyway, IMO this is relatively low priority and not worthy of 10.1.
But there are two remaining mysteries: (1) how does TBB malloc trigger
non-determinism in Symtab, and (2) is there a technical mistake in
Symtab that TBB malloc exposes that GNU glibc doesn't.

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/136)
