### ISSUE TITLE
hpcrun or interrupts change the output from hpcstruct

### ISSUE THREAD

**Issue by mwkrentel** [HPCToolkit/hpctoolkit#142]
I'm seeing a strange problem where hpcrun or its interrupts break
hpcstruct, where "break" means that struct produces a different
answer.

Use hpcstruct to analyze itself, both with and without hpcrun.
For example:

```
export LD_LIBRARY_PATH=/path/to/install/lib/hpctoolkit/ext-libs/

./hpcstruct-bin hpcstruct-bin -o out-native

hpcrun -e REALTIME@20000 ./hpcstruct-bin hpcstruct-bin -o out-hpcrun
```

In my example, the "first diff" is as follows at 0x4198fd which has a
different inline location in the two struct files.  This is 62% of the
way into the file, so there are probably only a few such diffs, or just one.

```
diff -u out-native out-hpcrun

  <A i="259851" l="125" f="/usr/include/c++/7/ext/new_allocator.h" n="&lt;inline&gt;" v="{}">

- <S i="259852" l="125" v="{[0x419776-0x41977b) [0x41978b-0x419790)
  [0x4197cb-0x4197d2) [0x419863-0x41986a) [0x4198b1-0x4198bd)
  [0x4198c6-0x4198cf) [0x4198e5-0x4198ea) [0x419911-0x419918)
  [0x41992e-0x419933) [0x41994f-0x419956) [0x419966-0x419970)
  [0x419984-0x41998b)}"/>

+ <S i="259852" l="125" v="{[0x419776-0x41977b) [0x41978b-0x419790)
  [0x4197cb-0x4197d2) [0x419863-0x41986a) [0x4198b1-0x4198bd)
  [0x4198c6-0x4198cf) [0x4198e5-0x4198ea) [0x4198fd-0x41990c)
  [0x419911-0x419918) [0x41992e-0x419933) [0x41994f-0x419956)
  [0x419966-0x419970) [0x419984-0x41998b)}"/>

-     <S i="260417" l="125" v="{[0x4198fd-0x41990c)}"/>
```

The source looks like:

```
114       // __p is not permitted to be a null pointer.
115       void
116       deallocate(pointer __p, size_type)
117       {
118 #if __cpp_aligned_new
119         if (alignof(_Tp) > __STDCPP_DEFAULT_NEW_ALIGNMENT__)
120           {
121             ::operator delete(__p, std::align_val_t(alignof(_Tp)));
122             return;
123           }
124 #endif
125         ::operator delete(__p);
126       }
```

Objdump has:

```
4198ef:       48 8b bd e8 fc ff ff    mov    -0x318(%rbp),%rdi
4198f6:       e8 45 51 00 00          callq  41ea40 <_ZNSt7__cxx1110 ... >
4198fb:       eb d2                   jmp    4198cf <_ZN5BAnal6Struct13makeStructure ... >
4198fd:       4c 89 e7                mov    %r12,%rdi
419900:       e8 6b fd fe ff          callq  409670 <_ZdlPv@plt>
419905:       eb e8                   jmp    4198ef <_ZN5BAnal6Struct13makeStructureENSt7 ... >
```

This example is on mic.cs, gcc 7.3.1, dyninst 10.1.0, intel-tbb 2019.4.
Some notes:

1. Same result with and without threads.

2. Same result with fast or slow interrupt rates, even a rate so slow
that hpcstruct finishes before the first interrupt.

3. The difference in output is deterministic.  With any number of
threads and sampling rate, I always get the same (modified) answer.
At least, I haven't seen any variation in the answer.

4. I'm suspicious of Intel TBB and transactional memory.  This may be
related to issue #136.

5. Try the experiment: turn off TM in Intel TBB.

6. Try the experiment: try dyninst 9.3.2 which doesn't use TBB.

7. Try hpcrun or interrupts in dyninst unit test.

Or, maybe it has nothing to do with interrupts.  Maybe it's something
with how we link in libhpcrun.so with LD_PRELOAD.  That would explain
(2) and (3), but I don't know what it would be.

Btw, `hpcrun -e NONE hpcstruct` deadlocks, which is a different
problem.  (NONE only seems to deadlock when running hpcstruct, not
some random app.)

Anyway, we need to track this down.  Fundamentally, hpcrun is changing
the output of some program, so we need to understand the mechanics of
what goes wrong.

Maybe we can fix this in hpcrun, or maybe there's a restriction we
need to add to an application.

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/142)
