### ISSUE TITLE
anomalies in output from hpcstruct

### ISSUE THREAD

**Issue by mwkrentel** [HPCToolkit/hpctoolkit#143]
While running other tests, I've seen the following anomalies from
hpcstruct.  At least probably in hpcstruct, they look bad end-to-end
in the viewer, but without investigating, I can't rule out hpcprof or
something else.

Apologies for not providing more complete directions on how to
reproduce these.  So, step one is a more explicit identification of
the problem.  For now, I'll just put down a general description.

These are probably all long standing problems, and probably some of
them stem from bad dwarf info or bad dyninst output.

1. There are often multiple lines with the same proc name with the
same file and line info.

2. Struct simple (from binutils) doesn't work well for PLT functions.

3. Struct simple doesn't work well for binaries that don't have line
map info or are stripped.

4. Some viewer lines appear as Struct.cpp:0 with known file name but
unknown line number.

5. On ARM (the new zeroah at Wisc), demangled names appear with the
binary name appended.  For example, 'main (hpcstruct-bin)'.

**Comment by mwkrentel** [comment]
I opened a separate issue #145 for problem (1) above.
This looks like a problem in Struct Simple, not hpcstruct.

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/143)
