### ISSUE TITLE
master-gpu fails to compile with settings from master

### ISSUE THREAD

**Issue by blue42u** [HPCToolkit/hpctoolkit#148]
Using my (non-Spack) build script (with manually-built externals), the master-gpu branch currently doesn't compile. The same script works fine on master, and of course doesn't explicitly enable CUDA or any of the other new features. The errors are:
1. Missing support for libmbedtls in `configure.ac` and `prof-lean/Makefile.am` ([as mentioned previously](https://github.com/HPCToolkit/hpctoolkit/issues/144#issuecomment-531097758)):
```
../../../../../src/ref-hpctoolkit/src/lib/prof-lean/crypto-hash.c:67:10: fatal error: mbedtls/md5.h: No such file or directory
   67 | #include <mbedtls/md5.h>  // MD5
      |          ^~~~~~~~~~~~~~~
```
2. Some bad `#ifdef`'s in `banal/Fatbin.cpp`:
```
../../../../../src/ref-hpctoolkit/src/lib/banal/Fatbin.cpp: In function 'bool findCubins(ElfFile*, ElfFileVector*)':
../../../../../src/ref-hpctoolkit/src/lib/banal/Fatbin.cpp:268:7: error: 'writeCubins' was not declared in this scope
  268 |       writeCubins(elfFileVector);
      |       ^~~~~~~~~~~
```
3. And a missing argument to a couple of function calls in `hpcrun/sample-sources/papi.c`:
```
../../../../../src/ref-hpctoolkit/src/tool/hpcrun/sample-sources/papi.c: In function 'process_event_list':
../../../../../src/ref-hpctoolkit/src/tool/hpcrun/sample-sources/papi.c:434:45: warning: passing argument 1 of 'hpcrun_set_new_metric_info_and_period' from incompatible pointer type [-Wincompatible-pointer-types]
  434 |       hpcrun_set_new_metric_info_and_period(strdup(buffer),
      |                                             ^~~~~~~~~~~~~~
      |                                             |
      |                                             char *
In file included from ../../../../../src/ref-hpctoolkit/src/tool/hpcrun/sample-sources/papi.c:86:
../../../../../src/ref-hpctoolkit/src/tool/hpcrun/metrics.h:139:56: note: expected 'kind_info_t *' {aka 'struct kind_info_t *'} but argument is of type 'char *'
  139 | int hpcrun_set_new_metric_info_and_period(kind_info_t *kind, const char* name,
      |                                           ~~~~~~~~~~~~~^~~~
---snip---
../../../../../src/ref-hpctoolkit/src/tool/hpcrun/sample-sources/papi.c:443:40: warning: passing argument 1 of 'hpcrun_set_new_metric_info_and_period' from incompatible pointer type [-Wincompatible-pointer-types]
  443 |  hpcrun_set_new_metric_info_and_period("idleness",
      |                                        ^~~~~~~~~~
      |                                        |
      |                                        char *
In file included from ../../../../../src/ref-hpctoolkit/src/tool/hpcrun/sample-sources/papi.c:86:
../../../../../src/ref-hpctoolkit/src/tool/hpcrun/metrics.h:139:56: note: expected 'kind_info_t *' {aka 'struct kind_info_t *'} but argument is of type 'char *'
  139 | int hpcrun_set_new_metric_info_and_period(kind_info_t *kind, const char* name,
      |                                           ~~~~~~~~~~~~~^~~~
---snip---
```

I can work around (1) easily, but (2) and (3) need some more detailed work.

**Comment by Jokeren** [comment]
Please use spack instead of manually built externals.

I thought I fixed (1), maybe I didn't...

I haven't seen problem (2) before.

To solve (3), you can disable PAPI for now.

**Comment by Jokeren** [comment]
https://github.com/HPCToolkit/hpctoolkit/blob/master-gpu/configure.ac#L2832

I found mbedtls here

**Comment by blue42u** [comment]
I have very good reasons for using manually-built externals. Mostly because when you have 3 different versions of Elfutils, Dyninst and HPCToolkit running around Spack starts to choke a bit. Especially if you make edits to the source files and need to recompile.

I'll edit my scripts for (1), didn't realize there was an option in now.

**Comment by mwkrentel** [comment]
@blue42u You should give us more detail about how you tried to build
master-gpu.  This reads too much like, "I tried a custom, non-standard
build and it didn't work."

What rev of hpctoolkit and master-gpu are you using (commit hash) ?
What compiler and its rev?
You're using outside builds of the prereqs, so what versions of those
and how did you build them?
Show us your build script and the hpctoolkit summary at the end of
configure.

However, in this case, I was able to figure out what is going on.

(1) is pilot error.  The master-gpu branch requires mbedtls.

(2) I can tell that you're using a old version of dyninst, or at least
something that fails the "does dyninst support cuda" configure test.

The Fatbin.cpp file is sloppy in how it uses DYNINST_USE_CUDA.  Part
of the code tests for it, and part of the code just assumes it's
always available.

I'll put this on @jokeren's to-do list to fix before the merge.

In the meantime, a more recent dyninst will fix this.

(3) is an outright bug, with mismatched type signatures for
hpcrun_set_new_metric_info_and_period.

I'm surprised this is only a warning.  What compiler are you using?

I'm even more surprised that when I build this on gpu.cs with gcc
7.3.0, I don't even get a warning, not even with -Wall.  How is that
possible??

Again, on @jokeren's to-do list to fix.

**Comment by blue42u** [comment]
> @blue42u You should give us more detail about how you tried to build
> master-gpu. This reads too much like, "I tried a custom, non-standard
> build and it didn't work."

Its only a little difficult to give meaningful detail when you have a custom, non-standard build, and it doesn't work.

> 
> What rev of hpctoolkit and master-gpu are you using (commit hash) ?
> What compiler and its rev?
> You're using outside builds of the prereqs, so what versions of those
> and how did you build them?
> Show us your build script and the hpctoolkit summary at the end of
> configure.

Right, knew I forgot something.

Latest as of a week ago (which is still latest). GCC 9.2.1 as shipped by Debian Unstable. I can give versions for the deps if needed, Cuda isn't one of them. I can *maybe* munge together a configure line for HPCToolkit.

You don't want to see my build script. Let's just leave it at that.

> 
> However, in this case, I was able to figure out what is going on.
> 
> (1) is pilot error. The master-gpu branch requires mbedtls.

Accurate, I've adjusted accordingly, and made a mental note to remember to update OPs when I have time in the future.

> 
> (2) I can tell that you're using a old version of dyninst, or at least
> something that fails the "does dyninst support cuda" configure test.
> 
> The Fatbin.cpp file is sloppy in how it uses DYNINST_USE_CUDA. Part
> of the code tests for it, and part of the code just assumes it's
> always available.
> 
> I'll put this on @Jokeren's to-do list to fix before the merge.
> 
> In the meantime, a more recent dyninst will fix this.

To be entirely honest, until a few moments ago I didn't know my Dyninst supported Cuda. I'll adjust my build script to make use of this fact.

> 
> (3) is an outright bug, with mismatched type signatures for
> hpcrun_set_new_metric_info_and_period.
> 
> I'm surprised this is only a warning.

There is also an error later down, I snipped it out because they all refer to the same place and same logical error.

> What compiler are you using?
> 
> I'm even more surprised that when I build this on gpu.cs with gcc
> 7.3.0, I don't even get a warning, not even with -Wall. How is that
> possible??
> 
> Again, on @Jokeren's to-do list to fix.

---

Given that all these have workarounds, (1) and (2) are really my own errors, and (2) and (3) have been copied with more detail into #144, I'm going to close this one. No point in duplicates.

**Comment by mwkrentel** [comment]
I should clarify one thing wrt cuda.  The --with-cuda option is
optional and AFAIK, the options for with and without are handled
correctly.  This mostly affects hpcrun.

The problem you ran into in (2) is that you have a dyninst that
doesn't support analyzing cubins.  This is for hpcstruct.

Configure tests for this and sets DYNINST_USE_CUDA.  Until recently,
both with and without cases worked correctly, until ....

I'm surprised and curious why your dyninst would fail the 'supports
cuda' test.  This goes back at least to 10.0.0 which is almost a full
year old now.

----------

Btw, hpctoolkit produces a summary of the build configuration at the
end of configure.  Even if you don't save it to a file (I always do),
there is a copy in config.log in the build directory.  Look for
'HPCToolkit summary'.
