### ISSUE TITLE
hpcrun needs to record meta-data in hpcrun files

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpctoolkit#15]
hpcrun needs to record meta-data about the execution including the node id and thread id (or thread ids) it ran on.

**Comment by laksono** [comment]
I recommend to record also the command line. Sometimes we forget the command line to produce the measurements.

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/15)
