### ISSUE TITLE
<program root> and <thread root> should not clickable in hpcviewer

### ISSUE THREAD

**Issue by laksono** [HPCToolkit/hpctoolkit#16]
In hpcviewer, we need to avoid users to click <program root> and <thread root> nodes and showing the source code of libmonitor. These special nodes should be unclickable. Either hpcviewer needs to "filter" the nodes or hpcrun or hpcprof has to be smart  enough to avoid linking the special nodes to the source files:

    <File i="35086" n="./src/home/la5/git/hpctoolkit-externals/libmonitor/libmonitor/src/pthread.c"/>
    <File i="35089" n="./src/home/la5/git/hpctoolkit-externals/libmonitor/libmonitor/src/main.c"/>
    <File i="35092" n="./src/home/la5/git/hpctoolkit-externals/libmonitor/libmonitor/src/mpi_init_c.c"/>

**Comment by jmellorcrummey** [comment]
I believe that these nodes only have hyperlinks when libmonitor.so is not stripped. It is normally stripped (for this exact reason) unless you compile with --enable-develop.
