### ISSUE TITLE
Change the way hpcrun specifies options without frequencies or periods

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpctoolkit#19]
Options such as BLOCKTIME, OMP_MUTEX, OMP_IDLE don't require periods or frequencies like other events specified using -e. We should use a different syntax, e.g., --blocktime, --omp-mutex, or --omp-idle rather than having them as events.

**Comment by jmellorcrummey** [comment]
We should consider a similar adjustment to environment variables used by statically-linked executables. Perhaps adding a HPCRUN_SYNTHETIC_METRICS environment variable with --blocktime, --omp-mutex, or --omp-idle

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/19)
