### ISSUE TITLE
fnbounds2 doesn't support static binaries

### ISSUE THREAD

**Issue by mwkrentel** [HPCToolkit/hpctoolkit#193]
I think the new hpcfnbounds2 program is badly broken for the static
case.  Maybe it doesn't support the static case or doesn't understand
static binaries, I don't know.

Anyway, running hpcfnbounds2 on a static binary results in a runaway
memory usage.  On the static 'hello, world' binary (1 meg), I killed
it after it grew to 8 Gig and produced no output.

I'm guessing this is broken everywhere for static binaries.

But as a specific example, I built today's toolkit (ac3444ce6c) on
gpu.cs.  Look in the following directory for the 'hello world' source
and static binary.

gpu.cs:  ~krentel/static/Save-1

I added the C/C++ static libraries to gpu.cs so that gcc/g++ should be
able to compile fully static binaries.  All it takes is 'hello, world'.

Btw, support for static binaries is necessary for machines like Cray
and hpclink.

@martyitz

**Comment by martyitz** [comment]
It’s never been tried before on static binaries.  I presume this is NOT a showstopper for the release.
Do static binaries matter to the Trilabs?

	Marty

**Comment by mwkrentel** [comment]
I don't think the Trilabs run static binaries.  But it's the primary
or only way of running on Cray, including the main machine at Argonne.
So, it's a case we absolutely must support.

It's not a blocker now for the release.  But it is a blocker for fnbounds2
ever becoming the primary fnbounds program.

**Comment by martyitz** [comment]
> On Jan 31, 2020, at 1:42 PM, Mark W. Krentel <notifications@github.com> wrote:
> 
> Anyway, running hpcfnbounds2 on a static binary results in a runaway
> memory usage. On the static 'hello, world' binary (1 meg), I killed
> it after it grew to 8 Gig and produced no output.
> 
> I'm guessing this is broken everywhere for static binaries.
> 
It is scanning the .plt section and finding way too many functions.  I think it’s not checking for the end of the section,
but I am not yet sure.  Why does a static executable have a .plt section anyway?

	Marty

**Comment by mxz297** [comment]
@martyitz One reason that static executable has a .plt section is to enable function call dispatch based on CPU types. For example, on different CPUs, memcpy can have different implementation (by using different instructions). The compiler folks decided that this is a nice feature to have even for statically linked binaries to improve performance.

**Comment by martyitz** [comment]
The .plt appears to be malformed -- it says each entry is zero-length.
Fixed in the fnbounds branch.
