### ISSUE TITLE
profiling with multiple events may fail for old Linux kernel (2.6.x) 

### ISSUE THREAD

**Issue by laksono** [HPCToolkit/hpctoolkit#20]
This command cause machine rebooting (or shutdown) on mic (linux kernel 2.6.x):

/home/la5/pkgs/hpctoolkit/bin/hpcrun -dd LINUX_PERF -e ix86arch::UNHALTED_CORE_CYCLES \
  -e ix86arch::INSTRUCTION_RETIRED \
  -e ix86arch::BRANCH_INSTRUCTIONS_RETIRED \
  -e ix86arch::MISPREDICTED_BRANCH_RETIRED -t \
  /home/la5/pkgs/hpctoolkit/bin/hpcstruct /home/la5/pkgs/hpctoolkit/libexec/hpctoolkit/hpcstruct-bin

However running with PERF::CYCLES on nancy (kernel 2.6.32) works just fine.
Not sure what was the problem.

**Comment by mwkrentel** [comment]
I've tried this with mult-kernel on the front ends of davinci and
biou, both running RH 6.x and kernel 2.6.32.

Works for me, so I'll close this.
