### ISSUE TITLE
Each component should put a version string in its output.

### ISSUE THREAD

**Issue by martyitz** [HPCToolkit/hpctoolkit#203]
hpcrun (and hpcfnbounds/hpcfnbounds2) should write to the .log file in the measurements
     directory.

hpcstruct should write to the .struct file

hpcprof and hpcprof-mpi should write to the database directory.

The version string should include the name, the git commit level, the spack info,
the build date, and the builder's ID.

Doing so would enable understanding various forms of pilot error or confusion, and ensure
we understand exactly what version of the tools wrote what data.

**Comment by martyitz** [comment]
It should also incorporate the name of the machine on which it was run, and a timestamp.

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/203)
