### ISSUE TITLE
<partial call paths> appears as an interior tree node with deep wave

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpctoolkit#212]
<img width="412" alt="image" src="https://user-images.githubusercontent.com/3926112/74538746-7635fd00-4f02-11ea-8642-bfdbe8777618.png">

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/212)
