### ISSUE TITLE
can't unwind out of std::condition_variable::wait on x86

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpctoolkit#213]
<img width="660" alt="image" src="https://user-images.githubusercontent.com/3926112/74539171-33285980-4f03-11ea-8d9d-f9c0881af4bc.png">

**Comment by jmellorcrummey** [comment]
@blue42u Please upload a tar file onto box that contains a copy of the following libraries that you used when profiling deep wave (on your home rig?):

```
/lib/x86_64-linux-gnu/libpthread-2.29.so
/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28
```

I need to look at the binaries to understand the root cause of the unwind problem you encountered in std::condition_variable::wait.

**Comment by blue42u** [comment]
Here you are: https://rice.box.com/s/fs97ix2c4qabgjvh1wpeldmdxodb6v43

**Comment by jmellorcrummey** [comment]
Do you still have a log file from the deep wave execution in your measurements directory? That would also be helpful for tracking down this problem.

**Comment by blue42u** [comment]
I believe the database you're looking at is the same one I gave Xiaozhu: https://rice.box.com/s/ugwziimczi95o1bv03u2bs3xtki0qh5i.

Here's a log file for from fresh run too: [python3-000000-000-007f0101-498772-0.log](https://github.com/HPCToolkit/hpctoolkit/files/4233711/python3-000000-000-007f0101-498772-0.log).

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/213)
