### ISSUE TITLE
Treat targXXXX as unknown procedures 

### ISSUE THREAD

**Issue by mxz297** [HPCToolkit/hpctoolkit#219]
When we use hpcstruct file, the "targXXX" functions from Dyninst representing stripped functions. Since "targXXX" functions are semantics equivalent to unknown procedures, we would like to augment it with virtual address and load module. This issue is just a reminder for myself.

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/219)
