### ISSUE TITLE
CUPTI Confuses the Unwinder w/ Fnb2 (Deepwave is Confusing, part 4)

### ISSUE THREAD

**Issue by blue42u** [HPCToolkit/hpctoolkit#225]
Unwind errors pulled out of the log files from Deepwave runs, part 4. All referenced binaries and measurements directories are [uploaded on Box](https://rice.box.com/s/qqbzt23sfx1e9ja2ogx19g3nc5n159zm).

HPCToolkit source is `pytorch` + `master` - #231 + #199.

Runs with Fnbounds2 occasionally get lost when unwinding out of CUDA libraries.

Unwind information is not always available, according to `objdump -WF` (`--debug-dump=frames-interp`). Frames missing info are marked with `[E]`.

    Key: $(objdump -WF ... | grep -c 'FDE\|CIE')/diff [fnb2-fnb] augment errors
    libcudart.so.10.1.243: ~1327/-6 [1478-1484] 
    libcudnn.so.7.6.5: ~44812/2225 [47237-45012] 
    libcupti.so.10.1.132: ~9056/1327 [10677-9350]
    libcusparse.so.10.3.0.243: ~11469/4 [11637-11633]

    ==== Seen 108 times: ====
    [ ] __cudaInitModule (libcudart.so.10.1.243) @ ??:?+0x19cbb ??:?+0x1cce2 ??:?+0x259ad ??:?+0x2662a ??:?+0x2704e ??:?+0x2dcb5 ??:?+0x32236 ??:?+0x32237 ??:?+0x33a4d ??:?+0x38963 ??:?+0x38aca ??:?+0x38bbe
    [L] LOST at 0x1
    ==== Seen 21 times: ====
    [ ] cudaVDPAUSetVDPAUDevice (libcudart.so.10.1.243) @ ??:?+0x5f3e2 ??:?+0x5f3e4
    [L] LOST at 0x1
    ==== Seen 2 times: ====
    [ ] cudaGetExportTable (libcudart.so.10.1.243) @ ??:?+0x15b40
    [L] LOST at 0x0
    ==== Seen 1 times: ====
    [ ] cudaPeekAtLastError (libcudart.so.10.1.243) @ ??:?+0x4c244
    [L] LOST at 0x7f2a0db09398
    ==== Seen 1 times: ====
    [ ] __cudaPopCallConfiguration (libcudart.so.10.1.243) @ ??:?+0xcb61
    [L] LOST at 0x7ffc00000001
    ==== Seen 1 times: ====
    [ ] cudaVDPAUSetVDPAUDevice (libcudart.so.10.1.243) @ ??:?+0x5f3e4
    [E] ?? (libcudart.so.10.1.243) @ ??:0+0x67ce0
    ==== Seen 5 times: ====
    [ ] __cudaInitModule (libcudart.so.10.1.243) @ ??:?+0x19cbb
    [E] ?? (libcusparse.so.10.3.0.243) @ ??:0+0x1ed5078
    [ ] cuptiActivityEnableContext (libcupti.so.10.1.132) @ ??:?+0xd030e
    ==== Seen 5 times: ====
    [ ] __cudaInitModule (libcudart.so.10.1.243) @ ??:?+0x19cbb
    [E] ?? (libcudnn.so.7.6.5) @ ??:0+0x9bce078
    [ ] cuptiActivityEnableContext (libcupti.so.10.1.132) @ ??:?+0xd030e
    ==== Seen 2 times: ====
    [ ] __cudaInitModule (libcudart.so.10.1.243) @ ??:?+0x3223d
    [ ] cuptiEventGroupSetDisable (libcupti.so.10.1.132) @ ??:?+0xfaf61
    [L] LOST at 0x7ffe311d7350

**Comment by Jokeren** [comment]
I suppose you were using both `REALTIME/CPUTIME` and `gpu=nvidia`.

What does `??:?` mean?

**Comment by blue42u** [comment]
`-t -e gpu=nvidia -e REALTIME@1000` to be precise.

`??:?` means no line information for that address. I used `addr2line` to get line info, so missing ones appear like that.

**Comment by Jokeren** [comment]
Can you show me the `addr2line` command you used?

Actually, it is quite hard to get line information from `libcupti.so`, as these binaries do not even have a `.debug_info` section.

These CUDA functions you've seen are not accurate function names. I remembered John used vdso branch support to get these function names.

**Comment by blue42u** [comment]
`addr2line -Cfse <binary> <address in hex>` (which also outputs the function name, which is how I got those too.)

These may not be the accurate function names, but I think they're the symbols said addresses land in. Either way, I just wanted an identifier to marge commonalities on, the exact offsets are more useful for unwind debugging.

**Comment by blue42u** [comment]
Updated OP to include data from the recent fnbounds2 update.

**Comment by martyitz** [comment]
The errant event count is a few tens of events out of more than 4,000,000.  The
problem does not need to be addressed.
