### ISSUE TITLE
Wrong CUBIN CFG for quicksilver

### ISSUE THREAD

**Issue by mxz297** [HPCToolkit/hpctoolkit#232]
@jmellorcrummey @Jokeren 

John found that we got unknown procedures for quicksilver when using `--gpucfg yes`:

![image](https://user-images.githubusercontent.com/1683713/75413543-731c1300-58eb-11ea-9ac4-4a26889aeb80.png)

I have determined that the struct file contains inconsistent information:

```
334       <S i="228" l="307" v="{[0x7c760-0x7c770)}"/>
...
345       <L i="239" l="238" f="/home/johnmc/hpctoolkit-gpu-samples/Quicksilver/src/MCT.cc" v="{[0x7bf40-0x7bf41)}">
...
387           <S i="279" l="307" v="{[0x7c740-0x7c790) [0x7c7e0-0x7c8d0)}"/>
```

Here line 387 shows a statement within a loop whose address range contains the statement at line 334 outside a loop. One instruction cannot be both inside and outside a loop. Therefore, this is a wrong struct file. 

I then went back many commits and the same issue persists, so Keren's latest RELA fix does not really cause this problem. I can only go back to a6f7962ad1041fe1834cb7fdfcea45258690e5f0, where it stops to compile on llnl.cs.

By enabling some debug output from hpcstruct, I believe the problem is in the CUBIN CFG parsing:

```
block:
stmt:  0x7c710 (16)  l=594  f='/home/johnmc/hpctoolkit-gpu-samples/Quicksilver/src/MCT.cc'
stmt:  0x7c720 (16)  l=594  f='/home/johnmc/hpctoolkit-gpu-samples/Quicksilver/src/MCT.cc'
stmt:  0x7c730 (16)  l=594  f='/home/johnmc/hpctoolkit-gpu-samples/Quicksilver/src/MCT.cc'
stmt:  0x7c740 (16)  l=307  f='/home/johnmc/hpctoolkit-gpu-samples/Quicksilver/src/MCT.cc'
stmt:  0x7c750 (16)  l=307  f='/home/johnmc/hpctoolkit-gpu-samples/Quicksilver/src/MCT.cc'
stmt:  0x7c760 (16)  l=307  f='/home/johnmc/hpctoolkit-gpu-samples/Quicksilver/src/MCT.cc'
out edges:  0x7c770 (direct)  0x7d570 (cond-take)


block:
stmt:  0x7c760 (16)  l=307  f='/home/johnmc/hpctoolkit-gpu-samples/Quicksilver/src/MCT.cc'
out edges:  0x7c760 (direct)  0x7c770 (direct)
```

We can see that address 0x7c760 appears in two different basic blocks, which corresponds to the instruction in the red box in the following screen shot:

![image](https://user-images.githubusercontent.com/1683713/75414025-d22e5780-58ec-11ea-829d-f52f7b7b6059.png)

It is not clear to me why we created a block at 0x7c760 without splitting the block that contains it and why we created a block at 0x7c760 at all.

**Comment by Jokeren** [comment]
@mxz297 , I'm not able to reproduce the same structure file.

Can you show me the `hpcrun` command and `hpcstruct` command you used? In addition, can you check if you used the new nvdisasm's result or the default nvdisasm? Thanks.

**Comment by jmellorcrummey** [comment]
@jokeren I apparently no longer have a binary with a cubin that matches the cubin that Max analyzed for us. 

It appears that the example that I had Xiaozhu looking at included a cubin that didn't match the nvdisasm output that max provided for us. 

This exercise may have been a false alarm. We really can't tell without the matching nvdisasm output from new nvdisasm.

**Comment by Jokeren** [comment]
@jmellorcrummey , it is a real bug.

The problem has nothing to do with the split policy. `CFGParser` splits every block with proper information. However, there is a nasty dangling block that has the same address with the basic block ends with `0x7c760`.

So the bug is caused by the way I associated dangling blocks back to functions. 

In the current implementation, if we have b1 and b2 in a function, and we have b3 as a dangling block. If b3.address > b1.front_inst.address, we create a link from b3 to b1. But b3 is still not reachable from the root block of the function. We can create a link from b1 to b3 regardless of their addresses.

I have fixed the bug and can make a pull request tomorrow.

**Comment by Jokeren** [comment]
Besides, another problem is that we are using a fake `nvdisasm`.

The dot graph generated by the fake `nvdisasm` contains every function in a cubin. Then, if we see a dangling block b1.address = b2.front_inst.address - 16 = b3.front_inst.address - 16, where b2 and b3 are from different functions, b1 could be either associated back to b2 or b3.

Our parser's logic with the real `nvdisasm`, however, is that each time we only parse a single global function to guarantee that instruction offset do not duplicate.
