### ISSUE TITLE
profiling fails if the user does not have read permission on exectuable

### ISSUE THREAD

**Issue by martyitz** [HPCToolkit/hpctoolkit#240]

**Comment by martyitz** [comment]
At LLNL, a user has execute permission on the executable, but not read permission, so that
callstack unwind fails.  

The tool should recognize this situation, and warn the user.

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/240)
