### ISSUE TITLE
Build failure with binutils@2.34

### ISSUE THREAD

**Issue by hainest** [HPCToolkit/hpctoolkit#242]
Spack recently upgraded to binutils@2.34 which causes build failures in HPCToolkit. I've put together a Spack PR that I'll submit shortly.

```
Seg.cpp: In member function 'std::__cxx11::string BinUtil::TextSeg::findProcName(bfd*, asymbol*) const':
Seg.cpp:488:39: error: cannot convert 'bfd*' to 'const asection*' {aka 'const bfd_section*'}
     bfd_vma secBase = bfd_section_vma(abfd, bfdSeg);
```

[hpctoolkit.gcc@8.3.0.log](https://github.com/HPCToolkit/hpctoolkit/files/4325886/hpctoolkit.gcc%408.3.0.log)

**Comment by mwkrentel** [comment]
@hainest I've updated master with a config test for binutils 2.34.
Master should now build either with old binutils <= 2.33.1 or with new
2.34.

I've also updated the spack recipe to allow 2.34 for master, and again
restricting to <= 2.33.1 for earlier versions.

So, I'll close the issue.
