### ISSUE TITLE
hpcfnbounds2 issues before making the default

### ISSUE THREAD

**Issue by mwkrentel** [HPCToolkit/hpctoolkit#253]
This issue is for discussion of issues that should be addressed before
making hpcfnbounds2 the default in master.

I've only started looking at this seriously, but for starters there
are two blocker issues.  Neither is particularly hard.

Overall, fnbound2 is much leaner and meaner, so this is something to
advertise as a feature improvement.

----------

(1) hpcfnbounds2 needs to support the '-c' option for writing C code
to stdout for hpclink.

You can run `hpcfnbounds -c <binary>` to see the syntax.  It has to be
valid and simple C code with exactly these variable names.  For
example:

```
$ gcc -g -O -static hello.c

$ file a.out
a.out: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux),
statically linked, for GNU/Linux 2.6.32, not stripped

$ hpcfnbounds -c a.out
unsigned long hpcrun_nm_addrs[] = {
  0x4002b8  /* start .init section, _init */,
  0x4002d2  /* end .init section */,
  0x4002e0  /* start .plt section */,
  0x4002f0  /* stripped_0x4002f0 */,
  0x400300  /* stripped_0x400300 */,
  0x400310  /* stripped_0x400310 */,
  ...
  0x494290  /* arena_thread_freeres */,
  0x49430a  /* _L_lock_18 */,
  0x494326  /* _L_unlock_34 */,
  0x494344  /* start .fini section, _fini */,
  0x49434d  /* end .fini section */
};
unsigned long hpcrun_nm_addrs_len = sizeof(hpcrun_nm_addrs) / sizeof(hpcrun_nm_addrs[0]);
unsigned long hpcrun_reference_offset = 0x400000;
int hpcrun_is_relocatable = 0;

$ hpclink gcc -g -O -static hello.c
hpclink: preliminary link 1 ...
hpclink: final link ...
hpclink: done

$ nm a.out | grep hpcrun
0000000000c9cb04 b _hpcrun_key
0000000000423600 T hpcrun_abort_w_info
0000000000409e80 T hpcrun_all_sources_finalize_event_list
000000000040a080 T hpcrun_all_sources_gen_event_set
0000000000409f00 T hpcrun_all_sources_init
0000000000409e40 T hpcrun_all_sources_process_event_list
000000000040a260 T hpcrun_all_sources_shutdown
...
```

We mostly use this for static binaries for hpclink, but -c should work
for any object file: .o, .so, dynamic or static executable.

On gpu.cs, both /usr/bin/gcc 4.8.5 and my spack module for 7.3.0 are
capable of creating static binaries.  It's mostly a matter of the
static libraries for libc, libstdc++, etc being installed.

----------

(2) Move the fnounds info messages to a -dd flag.

For normal execution, the hpcrun log files are supposed to remain
small, just a summary of what ran.  Anything else should be an
error/warning of some kind, or else debug info from a -dd flag.

Even errors are supposed to be rate limited, eg, stop printing the
same kind of error after the first 50 or so.

I'll add some infrastructure for this and then turn it over to Marty.
Hpcrun is all set up for this with -dd flags, but they don't carry
over to fnbounds across exec, so I'll have to add something.

----------

There's one other issue, not urgent or a blocker.  

(3) At some point, I'll restore fnbounds reporting memory usage to
hpcrun.  It doesn't have to restart fnbounds unless it goes seriously
runaway, but it should still report on usage.

I'll also try comparing things in the viewer.

@martyitz  @jmellorcrummey  @mxz297

**Comment by mwkrentel** [comment]
Ok, (1) and (2) above are done, and although I do want (3), it's not
urgent and not a blocker for switching the default.

Last I looked at this in the viewer, there were some odd differences
with some programs.  But it wasn't clear what "right" was or if
fnbounds2 was better or worse.  I'll see if I can post a more concrete
example.

**Comment by martyitz** [comment]
I'll restore it, as soon as you remove the kill of the server from hpcrun when it thinks
it's out of memory.

**Comment by martyitz** [comment]
For at least the new .plt.sec parsing, fnb2 is better than fnb.  I don’t know of any case
where fnb is better.  As far as I can tell, with my limited understanding of x86 assembler,
fnb sometimes shows non-functions as functions where fnb2 does not show them.

	Marty

**Comment by martyitz** [comment]
Restored memory usage reporting.
