### ISSUE TITLE
hpclink enhancements

### ISSUE THREAD

**Issue by martyitz** [HPCToolkit/hpctoolkit#258]
1.  hpclink -v should print the hpcfnbounds command it is launching.

2.  hpclink should have an option to preserve the .c and .o files from the
     hpcfnbounds -c invocation.

3.  hpclink should support the HPCRUN_FNBOUNDS_CMD  environment variable.
     (For consistency with hpcrun.)

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/258)
