### ISSUE TITLE
hpcprof doesn't handle paths for cubins and [vdso] right if a database is copied

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpctoolkit#269]
Reproducer:
```
hpcrun app
cp -r hpctoolkit-app-measurements mymeasurements
hpcprof my measurements

```
Problems:

-  hpcprof will access cubin and [vdso] binaries in hpctoolkit-app-measurements. I found this out when someone gave me a copy of their measurements directory
- for cubins, hpcprof will try to write a .cubin.relocate file into the original measurements directory
- for cubins, hpcprof-mpi may have multiple processes race and collide trying to produce a .cubin.relocate file

**Comment by jmellorcrummey** [comment]
- .cubin.relocate files are no longer written. 
- vdso files and cubin files should be recorded in the load map and processed like kernel files.

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/269)
