### ISSUE TITLE
Error within Dyninst

### ISSUE THREAD

**Issue by josephjohnjj** [HPCToolkit/hpctoolkit#274]
I have been trying to install HPCtoolkit. I have loaded boost as a module:

boost:
    modules:
      boost@1.72.0: boost/1.72.0
    variants: >
      +atomic +chrono +date_time +filesystem +system +thread +timer
      +graph +regex +shared +multithreaded ~debug
      ~mpi ~python ~iostreams ~numpy
      visibility=global
    buildable: False

I keep getting this error:

>> 615    CMake Error: Problem with archive_write_header(): Can't create 'boost_1_61_0/libs/geometry/doc/reference/algorithms/expand.qbk'
  >> 616    CMake Error: Current file: boost_1_61_0/libs/geometry/doc/reference/algorithms/expand.qbk
  >> 617    CMake Error: Problem extracting tar: /scratch/c37/jj8451/tmp/spack-stage/spack-stage-dyninst-10.1.0-t2rcoot3whi3ccpnico3gtvdasit2yip/spack-build/boost/src/boost_1_61
            _0.zip
     618    -- extracting... [error clean up]
  >> 619    CMake Error at boost-stamp/extract-boost.cmake:33 (message):
     620      error: extract of
     621      '/scratch/c37/jj8451/tmp/spack-stage/spack-stage-dyninst-10.1.0-t2rcoot3whi3ccpnico3gtvdasit2yip/spack-build/boost/src/boost_1_61_0.zip'
     622      failed
     623
     624
  >> 625    make[2]: *** [CMakeFiles/boost.dir/build.make:96: boost/src/boost-stamp/boost-download] Error 1
     626    make[2]: Leaving directory '/scratch/c37/jj8451/tmp/spack-stage/spack-stage-dyninst-10.1.0-t2rcoot3whi3ccpnico3gtvdasit2yip/spack-build'
  >> 627    make[1]: *** [CMakeFiles/Makefile2:548: CMakeFiles/boost.dir/all] Error 2

This is the error displayed in the log file

cd /scratch/c37/jj8451/tmp/spack-stage/spack-stage-dyninst-10.1.0-hqoy2tz72snuw5qjw5mwkkwl5ikoqqlt/spack-build/boost/src && /apps/cmake/3.16.2/bin/cmake -P /scratch/c37/jj8451/tmp/spack-stage/spack-stage-dyninst-10.1.0-hqoy2tz72snuw5qjw5mwkkwl5ikoqqlt/spack-build/boost/src/boost-stamp/verify-boost.cmake
cd /scratch/c37/jj8451/tmp/spack-stage/spack-stage-dyninst-10.1.0-hqoy2tz72snuw5qjw5mwkkwl5ikoqqlt/spack-build/boost/src && /apps/cmake/3.16.2/bin/cmake -P /scratch/c37/jj8451/tmp/spack-stage/spack-stage-dyninst-10.1.0-hqoy2tz72snuw5qjw5mwkkwl5ikoqqlt/spack-build/boost/src/boost-stamp/extract-boost.cmake
-- extracting...
     src='/scratch/c37/jj8451/tmp/spack-stage/spack-stage-dyninst-10.1.0-hqoy2tz72snuw5qjw5mwkkwl5ikoqqlt/spack-build/boost/src/boost_1_61_0.zip'
     dst='/scratch/c37/jj8451/tmp/spack-stage/spack-stage-dyninst-10.1.0-hqoy2tz72snuw5qjw5mwkkwl5ikoqqlt/spack-build/boost/src/boost'
-- extracting... [tar xfz]
CMake Error: Problem with archive_write_header(): Can't create 'boost_1_61_0/libs/geometry/doc/reference/algorithms/clear.qbk'
CMake Error: Current file: boost_1_61_0/libs/geometry/doc/reference/algorithms/clear.qbk
CMake Error: Problem extracting tar: /scratch/c37/jj8451/tmp/spack-stage/spack-stage-dyninst-10.1.0-hqoy2tz72snuw5qjw5mwkkwl5ikoqqlt/spack-build/boost/src/boost_1_61_0.zip
-- extracting... [error clean up]
CMake Error at boost-stamp/extract-boost.cmake:33 (message):
  error: extract of
  '/scratch/c37/jj8451/tmp/spack-stage/spack-stage-dyninst-10.1.0-hqoy2tz72snuw5qjw5mwkkwl5ikoqqlt/spack-build/boost/src/boost_1_61_0.zip'
  failed

make[2]: *** [CMakeFiles/boost.dir/build.make:96: boost/src/boost-stamp/boost-download] Error 1
make[2]: Leaving directory '/scratch/c37/jj8451/tmp/spack-stage/spack-stage-dyninst-10.1.0-hqoy2tz72snuw5qjw5mwkkwl5ikoqqlt/spack-build'
make[1]: *** [CMakeFiles/Makefile2:548: CMakeFiles/boost.dir/all] Error 2
make[1]: Leaving directory '/scratch/c37/jj8451/tmp/spack-stage/spack-stage-dyninst-10.1.0-hqoy2tz72snuw5qjw5mwkkwl5ikoqqlt/spack-build'
make: *** [Makefile:133: all] Error 2

**Comment by jmellorcrummey** [comment]
how did you try to install hpctoolkit?
- are you working with a recent clone of spack?
- did you initial the install with “spack install hpctoolkit”?
- are you using a custom “packages.yaml” file? if so, what is in it?
