### ISSUE TITLE
attributing gpu metrics to procedures in hpcprof

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpctoolkit#278]
in hpcrun, we attribute procedure-level gpu metrics to gpu procedures for nvidia gpus by attributing metrics such as threads and register usage, by attributing them to the first instruction in the procedure as a surrogate for the procedure itself. this leads to the confusing presentation in hpcviewer where the statement that represents the first machine instruction in a gpu procedure has values for these procedure-level metrics. 

we should adjust metric descriptions to indicate what exclusive-only metrics should be presented for procedures only. hpcprof can then propagate these exclusive metrics to the enclosing procedure and elide them from the statements.

Alternative approach: hpcviewer could present exclusive-only procedure-level metrics only at the procedure level, eliding them from statements and the aggregate view.

@laksono @mxz297

**Comment by Jokeren** [comment]
Almost done now

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/278)
