### ISSUE TITLE
No such file or directory: libiberty/demangle.h

### ISSUE THREAD

**Issue by chrisreidy** [HPCToolkit/hpctoolkit#287]
Hi
I get this error during make on Centos7 with AMD Rome processors
In file included from demangle.c:59:
/opt/ohpc/admin/UAbuild/hpctoolkit/hpctoolkit/src/include/gnu_demangle.h:68:10: fatal error: libiberty/demangle.h: No such file or directory
 #include <libiberty/demangle.h>

I have tried 'without-libiberty'
and 'with-libiberty=/path/to/externals/binutils'
There is also a /usr/include/demangle.h and a /usr/include/libiberty.h but no /usr/include/libiberty/demangle.h

**Comment by jmellorcrummey** [comment]
the only installation recommended these days is using “spack”, which will automatically configure and build packages that we depend upon. see the instructions on hpctoolkit.org.

**Comment by chrisreidy** [comment]
Thanks for the update.  Spack is an ecosystem that we have not implemented.  It is not designed for installing separate applications like cmake does.  So I will have to come up with something else

**Comment by jmellorcrummey** [comment]
Chris, spack is easier than you think.

You should consult the directions on hpctoolkit.org, but in most cases you should be able to install hpctoolkit with the following

git clone https://github.com/spack/spack

cd spack/bin
./spack spec hpctoolkit  #see what will be installed
./spack install hpctoolkit

**Comment by chrisreidy** [comment]
I will give that a try.  Thanks for the helpful suggestion

**Comment by chrisreidy** [comment]
Thanks.  That worked great.  The only wrinkle was I had to create a manual_mirror for openssl due to some strange connectivity issue that is not a problem with hpctoolkit

**Comment by jmellorcrummey** [comment]
Glad that worked for you!
