### ISSUE TITLE
hpcprof --metric-db depricated?

### ISSUE THREAD

**Issue by ian-bertolacci** [HPCToolkit/hpctoolkit#289]
Has the `--metric-db` option been depricated?
Using it seems to produce no effect.
Using the same hpcprof command on the same hpctoolkit-measurements directory with only the --metric-db option switched between 'yes' and 'no' produces the same set of files and all files are the same (accoriding to diff).

I have tried this on metrics collected using hpcrun both with and with-out tracing (`-t`) enabled.

Have metric-db files/folders become these hpctrace files?

This is somewhat realated to an issue in the Hatchet project (https://github.com/LLNL/hatchet/issues/60)

**Comment by jmellorcrummey** [comment]
The --metric-db flag is disabled for hpcprof. It should be available for hpcprof-mpi. We disabled them by default because (1) most people don't use them, and (2) they can be huge for applications that collect GPU metrics (of which there can be > 100). We are in the process of overhauling hpctoolkit to represent metrics in a sparse form rather than a dense form. Once we do that, the "metric-db" information will be collected by default once more.

hpctrace files are something completely different: they collect a sequence of call stack samples for a thread in an application. they are collected when using the -t option. they have no relation to metric-db info.

**Comment by ian-bertolacci** [comment]
Ok that is really confusing.
The manual implies that hpcprof-mpi is simply for performing the analysis faster by performing it in parallel.
The manual also does not include anything about metric database files or the --metric-db flag.

So to get metric-db files, I have to use hpcprof-mpi? Do I have to run hpcprof-mpi with the same number of processes as the number of processes used with hpcrun? 

Additionally, does this mean that `hpcstruct` and `hpctruct -j <OMP-THREADS>` are semantically different or produce different analysis?

**Comment by jmellorcrummey** [comment]
> Ok that is really confusing.
> The manual implies that hpcprof-mpi is simply for performing the analysis faster by performing it in parallel.

That is generally the case. However, we found that computing the --metric-db was so slow, it was something that we didn't want to support in hpcprof as a land mine that users would inadvertantly trigger that would cause their analysis to run excruciatingly slow.


> The manual also does not include anything about metric database files or the --metric-db flag.

We will correct that deficiency in the manual.  The --help message for hpcprof and hpcprof-mpi should be right. I believe we fixed that.

> So to get metric-db files, I have to use hpcprof-mpi? 

Yes.

> Do I have to run hpcprof-mpi with the same number of processes as the number of processes used with hpcrun?

No. The number of ranks you use in hpcprof-mpi is your choice and should be based on how many files you want to analyze. For instance, you might want to use 32 MPI ranks to analyze a hpctoolkit measurement database that contains hundreds of .hpcrun files.  You can even run a single-process version of hpcprof-mpi, if you choose. How to launch hpcprof-mpi depends upon your MPI implementation and perhaps batch manager on the system you are using. For instance, you might say:

`mpirun -np k hpcprof-mpi ...`

or 

`jsrun --np k hpcprof-mpi ...`

or

`srun hpcprof-mpi ...
`

Depending upon what MPI implementation you compiled with, you may even be able to run hpcprof-mpi on a single process without using an MPI launcher. (OpenMPI supports that.)


> Additionally, does this mean that hpcstruct and hpctruct -j <OMP-THREADS> are semantically different or produce different analysis?

They are semantically equivalent; the -j version just runs faster.

**Comment by ian-bertolacci** [comment]
> The --help message for hpcprof and hpcprof-mpi should be right. I believe we fixed that.

I'm not sure that it is, and it seems to contradict itself.
```
> hpcprof --version
hpcprof: A member of HPCToolkit, version 2020.03.01-release
git branch:  detached at 2020-02-29 (94ede4e6fa1e05e6)
spack spec:  hpctoolkit@2020.03.01%gcc@7.5.0~all-static~bgq~cray~cuda~mpi~papi arch=linux-ubuntu18.04-skylake/pnyrk63
install dir: [redacted]

> hpcprof --help
[... trimmed ...]
Options: Output:
  [... trimmed ...]
  --metric-db <yes|no>
                       Control whether to generate a thread-level metric
                       value database for hpcviewer scatter plots. {no}
[... trimmed ...]

> man hpcprof
[... trimmed ...]
   OPTIONS: OUTPUT
       [... trimmed ...]
       --metric-db yes | no
               If yes, generate a thread-level metric value database for hpcviewer scatter plots.  The default is yes.
[... trimmed ...]
```

**Comment by jmellorcrummey** [comment]
We have a new "spack" release dated 2020.06.12. I recommend moving to the newest release. We've cleaned up some, though perhaps not all of the documentation and help messages.

As I recall, we took the --metric-db option out of hpcprof because it was already disabled and the --help message didn't indicate that. It is present for hpcprof-mpi.

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/289)
