### ISSUE TITLE
Adjust hpctraceviewer and hpcviewer wrapper scripts for Java 8 and Java 9

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpctoolkit#29]
- Don't use option MaxPermSize with Java 8.  Java 8 VM reports "Ignoring option MaxPermSize; support was removed in 8.0"
- For Oracle JDK 9 java, the command "java -version" prints 
`java version "9.0.1" `
The hpctraceviewer and hpcviewer scripts complain that this is a version too old because it only inspects the minor number and finds 0. The scripts recommend using java 1.5 or higher.

**Comment by laksono** [comment]
This was fixed in the trunk several months ago. Unfortunately it wasn't in the release.
