### ISSUE TITLE
Java 9 compatibility issue for HPCToolkit GUIs

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpctoolkit#30]
See the warnings in bold below:

hpctraceviewer hpctoolkit-openmp-parse-database/
java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
**WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.eclipse.osgi.internal.baseadaptor.BaseStorage (file:/afs/cs.wisc.edu/u/j/o/johnmc/pkgs-src/viewers/INSTALL/libexec/hpctraceviewer/plugins/org.eclipse.osgi_3.7.2.v20120110-1415.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of org.eclipse.osgi.internal.baseadaptor.BaseStorage
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release**
!SESSION 2017-11-22 17:08:13.242 -----------------------------------------------
eclipse.buildId=unknown
java.version=9.0.1
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_U

**Comment by laksono** [comment]
The problem occurs within Eclipse library: org.eclipse.osgi.internal.baseadaptor.BaseStorage .
We need to check if the latest Eclipse fixes this.

**Comment by jmellorcrummey** [comment]
moved to java 11
