### ISSUE TITLE
Compile error with GCC 10

### ISSUE THREAD

**Issue by blue42u** [HPCToolkit/hpctoolkit#309]
@jmellorcrummey @mwkrentel I hate to report bugs just after a release, but compile errors are fairly critical:
```
$ spack install -j20 hpctoolkit %gcc@10.2.0
...
==> Installing hpctoolkit
==> No binary for hpctoolkit found: installing from source
==> hpctoolkit: Executing phase: 'autoreconf'
==> hpctoolkit: Executing phase: 'configure'
==> hpctoolkit: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j20'
...
     2355    /usr/bin/ld: gpu/.libs/libhpcrun_la-gpu-metrics.o:/tmp/deepthought/spack-stage/spack-stage-hpctoolkit-2020.08.03-7rwoundocvr6g357a5oirh
             qm74qbf6am/spack-src/src/tool/hpcrun/gpu/gpu-metrics.h:66: multiple definition of `gpu_inst_stall_all_t'; gpu/.libs/libhpcrun_la-gpu-ap
             plication-thread-api.o:/tmp/deepthought/spack-stage/spack-stage-hpctoolkit-2020.08.03-7rwoundocvr6g357a5oirhqm74qbf6am/spack-src/src/to
             ol/hpcrun/gpu/gpu-metrics.h:66: first defined here
  >> 2356    collect2: error: ld returned 1 exit status
```
Marking https://github.com/HPCToolkit/hpctoolkit/blob/f5853882147d18bed81127dfeeef2f68b5c58db0/src/tool/hpcrun/gpu/gpu-metrics.h#L64-L66 with a `typedef` fixes the error (and the rest of the compilation proceeds without issue).

For reference, GCC 10.0 (which I think is the first revision sensitive to this issue) was released in May of this year.

**Comment by mwkrentel** [comment]
@blue42u Would you like to submit a PR for this?

I remember long ago where this was a regular occurrence with binutils.
Seemed like every "new" rev of gcc (4.1, 4.4) would break some usage
in binutils.

@scottkwarren It's probably worth running regular tests that include the
latest version of gcc to test for build errors like this.  There are
some versions of Linux (arch linux, maybe more) that run the very
latest version of everything.

We may as well find the errors before someone else reports them.

**Comment by scottkwarren** [comment]
Good idea, I will try to enhance my nightly testing to run on the latest gcc as well. — skw
