### ISSUE TITLE
hpctraceviewer summary pane

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpctoolkit#34]
There are several features that could make the summary pane more usable:

- being able to see the summary as a pie chart. Sometimes it is hard to pick out colors when there are jagged contours.
- being able to zoom the summary pane. Sometimes, the depth of the summary pane is very small compared to the total height of the pane.

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/34)
