### ISSUE TITLE
hpcrun should error if perf events is used but not available

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpctoolkit#341]
if a user has specified that they want to measure a program using perf events, e.g. collect a cycles measurement, but /proc/sys/kernel/perf_event_paranoid doesn't have an appropriate value, the program should report an error to stderr and exit.

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/341)
