### ISSUE TITLE
hpcrun should error if one attempts to use CUPTI but CUPTI is disabled

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpctoolkit#342]
if a user has specified that they want to measure a GPU program using CUPTI, e.g. collect kernel profiles, but the kernel driver is not in a state that would permit that, hpcrun should report an error and exit.

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/342)
