### ISSUE TITLE
compilation of hpcrun-fmt.h

### ISSUE THREAD

**Issue by jgphpc** [HPCToolkit/hpctoolkit#343]
I have to build hpctoolkit without spack.

```
commit ad00b12
Author: Mark W. Krentel <krentel@rice.edu>
Date:   Tue Oct 27 00:22:10 2020 -0500
```

It fails because of:

> head hpctoolkit.git/src/lib/prof-lean/hpcrun-fmt.h

```
"$Id$\n"
"\n"
etc...
```

> gcc -DHAVE_CONFIG_H -I. -I../../../src/include -g -O3 -Wall
-I/apps/common/UES/sandbox/jgp/production.git/easybuild/easyconfigs/h/hpctoolkit/hpctoolkit.git/src
-I/apps/common/UES/sandbox/jgp/production.git/easybuild/easyconfigs/h/hpctoolkit/hpctoolkit.git/src
-I/users/piccinal/easybuild/dom/haswell/software/mbedtls/v2.24.0-CrayGNU-20.08/include
-I/apps/dom/UES/jenkins/7.0.UP02/gpu/easybuild/tools/software/elfutils/0.180-CrayGNU-20.08/include
-MT libHPCprof_lean_la-hpcrun-fmt.lo -MD -MP -MF
.deps/libHPCprof_lean_la-hpcrun-fmt.Tpo -c hpcrun-fmt.c  -fPIC -DPIC -o
.libs/libHPCprof_lean_la-hpcrun-fmt.o

```
In file included from hpcrun-fmt.c:84:
hpcrun-fmt.h:1:1: error: expected identifier or '(' before string constant
 "$Id$\n"
 ^~~~~~~~
hpcrun-fmt.c: In function 'hpcrun_fmt_hdr_fwrite':
hpcrun-fmt.c:131:10: error: 'HPCRUN_FMT_Magic' undeclared (first use in this function)
   fwrite(HPCRUN_FMT_Magic,   1, HPCRUN_FMT_MagicLen, fs);
          ^~~~~~~~~~~~~~~~
```

Is there a compilation flag that could help me compile hpcrun-fmt.h ?

jg.

**Comment by jgphpc** [comment]
I moved to `hpctoolkit-release-2020.08`, sorry for the noise.

**Comment by RemiLacroix-IDRIS** [comment]
Hi @jgphpc,

Would you mind give some more info regarding how your fixed this issue?

I have stumbled on the same problem except that I am using Spack. It uses commit d9d13c705d81e5de38e624254cf0875cce6add9a.
