### ISSUE TITLE
Custom tracing annotations

### ISSUE THREAD

**Issue by hyviquel** [HPCToolkit/hpctoolkit#346]
Hey guys,

My research group is experimenting HPCToolkit to profile MPI programs and I was wondering if there is anyway to add custom markers/tags/annotation) on the tracing timeline just like with NVTX (see [here](https://developer.nvidia.com/blog/cuda-pro-tip-generate-custom-application-profile-timelines-nvtx/) for example).

I didn't see anything about it in the documentation but you guys might have a solution.
Thanks

**Comment by Jokeren** [comment]
Hi @hyviquel, currently we don't support nvtx.

If you are using HPCToolkit's trace viewer, on the right side you can see a "call stack" pane. You can choose the level of call stack to focus. For example, if you want to annotate function *foo*, you can select *foo* in the call stack pane, and then the trace viewer will render *foo* and all functions below *foo* with the same color on the time line.

Not sure if this meets your requirement?

**Comment by hyviquel** [comment]
This might help, thanks!
