### ISSUE TITLE
Error messages from hpcstruct

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpctoolkit#35]
@mwkrentel 

Below is what I see when I gave the wrong path for the file I was trying to analyze. I think we could do better. If we can't find the file, we should just end after the first error message.

~/parallel-parsing/hpctoolkit-banal/INSTALL/bin/hpcstruct openmp-parse           
WARNING: SymtabAPI was unable to open: openmp-parse
WARNING: The static inline support does not work cross platform,
WARNING: so check that this file has the same arch type as hpctoolkit.
ERROR: [Diagnostics::FatalException] banal caught unexpected signal 11 [../../../../src/lib/banal/Struct-Inline.cpp:128]

**Comment by jmellorcrummey** [comment]
@mwkrentel this problem now exists in master

**Comment by mwkrentel** [comment]
Now fixed in mult-kernel, so I'll close this.

I added one message for the case of attempting to open a non-ELF file.
Previously, it failed silently.

And I've verified about 10 different bad inputs that the error message
is at least mostly-informative.
