### ISSUE TITLE
When I make the project, there is an error in the process.

### ISSUE THREAD

**Issue by TruNcat3** [HPCToolkit/hpctoolkit#353]
the error log is the following:
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../../../src/include -g -O3 -Wall -faligned-new -I/home/gg/work/hpctoolkit/src -I/home/gg/work/hpctoolkit/src -Ino/include -Ino -MT cuda/libHPCbanal_la-CFGParser.lo -MD -MP -MF cuda/.deps/libHPCbanal_la-CFGParser.Tpo -c cuda/CFGParser.cpp  -fPIC -DPIC -o cuda/.libs/libHPCbanal_la-CFGParser.o
In file included from cuda/CFGParser.hpp:8:0,
                 from cuda/CFGParser.cpp:1:
cuda/DotCFG.hpp:12:10: fatal error: CFG.h: No such file or directory
 #include <CFG.h>
          ^~~~~~~
compilation terminated.

So, where is the 'CFG.h'?

**Comment by jmellorcrummey** [comment]
the file CFG.h comes from an external dependence. we now use the spack package manager to build and install hpctoolkit. spack manages all of our external dependences. 

see the build instructions on hpctoolkit.org here:

http://hpctoolkit.org/software-instructions.html

**Comment by TruNcat3** [comment]
Fine, when I use "spack install hpctoolkit ", the error log is as following with 2 parts:
**1.** 

==> papi: Executing phase: 'autoreconf'
==> papi: Executing phase: 'configure'
==> Error: RuntimeError: PAPI requires a Fortran compiler to build

/home/gg/work/spack/spack/var/spack/repos/builtin/packages/papi/package.py:102, in fortran_check:
         99    def fortran_check(self):
        100        if not self.compiler.fc:
        101            msg = 'PAPI requires a Fortran compiler to build'
  >>    102            raise RuntimeError(msg)

**2.**
==> dyninst: Executing phase: 'cmake'
==> dyninst: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j8'

18 errors found in build log:
     344    [ 30%] Building C object CMakeFiles/dyninstAPI_RT_static.dir/src/RT
            linux.c.o
     345    [ 33%] Building C object CMakeFiles/dyninstAPI_RT_static.dir/src/RT
            heap.c.o
     346    [ 36%] Building C object CMakeFiles/dyninstAPI_RT.dir/src/RTheap-li
            nux.c.o
     347    [ 40%] Building C object CMakeFiles/dyninstAPI_RT_static.dir/src/RT
            heap-linux.c.o
     348    [ 43%] Building C object CMakeFiles/dyninstAPI_RT_static.dir/src/RT
            thread.c.o
     349    [ 46%] Building C object CMakeFiles/dyninstAPI_RT_static.dir/src/RT
            space.S.o
  >> 350    /tmp/gg/spack-stage/spack-stage-dyninst-10.2.1-rltoh7pskjzcxhvugfzm
            ersu6vzz7zrs/spack-src/dyninstAPI_RT/src/RTspace.S:1:1: error: expe
            cted identifier or '(' before '.' token
     351     .file "RTspace.s"
     352     ^
  >> 353    /tmp/gg/spack-stage/spack-stage-dyninst-10.2.1-rltoh7pskjzcxhvugfzm
            ersu6vzz7zrs/spack-src/dyninstAPI_RT/src/RTspace.S:4:44: error: str
            ay '@@' in program
     354     .type DYNINSTstaticHeap_512K_lowmemHeap_1, @object
     355                                                ^
  >> 356    /tmp/gg/spack-stage/spack-stage-dyninst-10.2.1-rltoh7pskjzcxhvugfzm
            ersu6vzz7zrs/spack-src/dyninstAPI_RT/src/RTspace.S:8:40: error: str
            ay '@@' in program
     357     .type DYNINSTstaticHeap_16M_anyHeap_1, @object


About the first question, I have installed the gfortran. But it seems useless.

About the second question, I have no idea to solve it.

**Comment by Jokeren** [comment]
@TruNcat3 

For the first issue, run `spack compiler find` to find available compilers before building hpctoolkit.

For the second issue, try using an older version of cmake. For example, `spack install hpctoolkit ^cmake@3.18.1`.

https://github.com/dyninst/dyninst/issues/923

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/353)
