### ISSUE TITLE
CPUTIME profile overcounts time when thread is sleeping

### ISSUE THREAD

**Issue by martyitz** [HPCToolkit/hpctoolkit#356]
The interrupt handler is currently using the realtime delta between the previous and current interrupts as the
duration of the current event.  If the thread goes to sleep after the previous interrupt, it effectively substitutes
realtime for cputime, which overcounts.  The problem is especially visible in the rajatest code, which has
two OMP phases and many seconds of non-OMP work during which all the worker threads are sleeping.

A cross-check for correctness would be to run the test code with /bin/time and compare the reported
user time with the Experiment Aggregated Metrics from the database; they should match within a few percent.

**Comment by martyitz** [comment]
The fix is to use the CPU time to compute the metrics for CPUTIME, and the real time to compute
the metric for REALTIME, rather than real time for both.

**Comment by jmellorcrummey** [comment]
fixed with PR #356
