### ISSUE TITLE
hpcstruct could describe PLT stubs better

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpctoolkit#36]
When using hpctoolkit to analyze openmp-parse, both libparseAPI.so and libsymtabAPI.so are linked into the executable and my newest versions of these libraries use phase-fair reader writer locks provided by libcommon.so. Using the `banal-merge` branch, both libparseAPI.so and libsymtabAPI.so get PLT stubs for the reader/writer lock primitives (pfq_rwlock_read_lock, pfq_rwlock_read_unlock, pfq_rwlock_write_lock, and pfq_rwlock_write_unlock). hpcstruct's analysis of the PLT stubs yields procedure entries like the following:
    
```
<P i="153223" n="pfq_rwlock_write_unlock(pfq_rwlock_t&amp;, mcs_node_s&amp;)" ln="_Z23pfq_rwlock_write_unlockR12pfq_rwlock_tR10mcs_node_s" l="0" v="{[0x171660-0x171661)}">
      <S i="153224" l="0" v="{[0x171660-0x171670)}"/>
</P>
```

hpcviewer reports time in PLT stubs in libparseAPI.so and libsymtabAPI.so separately from the associated function implementation in libcommon.so. If we report PLT stubs separately, we should be able to tell that there is time in the PLT stubs and whose stubs they are. I like the idea of reporting time in the stubs separately. For very small routines, the cost of the stubs may approach the cost of the routine, so it is worth knowing about the stubs. I recommend that we name the procedure records we produce for a routine and stubs as follows:

```
pfq_rwlock_write_unlock(pfq_rwlock_t&amp;, mcs_node_s&amp;)@plt (libparseAPI.so)
pfq_rwlock_write_unlock(pfq_rwlock_t&amp;, mcs_node_s&amp;)@plt (libsymtabAPI.so)
pfq_rwlock_write_unlock(pfq_rwlock_t&amp;, mcs_node_s&amp;)
```
The last one is intended to be the real implementation in libcommon.so. This seems like the minimum that we should do.

Thinking about this further, I think that all procedures should be annotated with what load module they are from. We could use the following convention:

- any routine in the executable should have no notation where it is from
- any routine in a shared library should be annotated where it is from
- any PLT stub should always be annotated with the load module containing it
- inlined procedures should not be annotated with the load module in which they are inlined

Load module information should be displayed by default. Perhaps it should be suppressible with an   hpcviewer option.

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/36)
