### ISSUE TITLE
CUPTI_ERROR_NOT_INITIALIZED on summit with CUDA>=11.1.1

### ISSUE THREAD

**Issue by Jokeren** [HPCToolkit/hpctoolkit#367]
I ran into this problem with hpctoolkit master branch. It works fine with CUDA 11.1.0, but both CUDA 11.1.1 and CUDA 11.2.0 failed. Not sure if this is caused by the old CUDA driver on summit.

**Comment by Jokeren** [comment]
One solution to get around the driver problem.

https://github.com/HPCToolkit/hpctoolkit/blob/master/src/tool/hpcrun/gpu/nvidia/cuda-api.c#L315
https://github.com/HPCToolkit/hpctoolkit/blob/b500377bd9a81619face7a4cdccbe9f4b2121171/src/tool/hpcrun/gpu/nvidia/cuda-device-map.c#L180

Comment `Line 180` to eliminate calls to `cuDeviceGetAttribute` and do not insert entries to the device map on `Line 184`.

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/367)
