### ISSUE TITLE
cuda incompatibility

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpctoolkit#375]
While working on ascent (a summit like system), I found that if I built hpctoolkit with cuda 10.1.243 and then compiled a program with cuda 11.0.2, CUPTI startup would fail with 

FATAL: hpcrun failure: failure type = CUPTI result error, function cuptiActivitySetAttribute failed with error CUPTI_ERROR_NOT_INITIALIZED

We need to review how hpctoolkit works with various cuda and CUPTI. I could see that it was using CUPTI 11 even though it was compiled with CUDA 10 when the error occurred. I am not sure why we encounter a problem.

**Comment by Jokeren** [comment]
@jmellorcrummey hpctoolkit with cuda 11.0.1 profiling application with cuda 11.1.0 also failed. I reported a similar issue several days. It also impacted gvprof's experiments on summit. I will spend sometime to narrow down the cause.

**Comment by jmellorcrummey** [comment]
@mxz297 @Jokeren Based on our recent experiences, we have found that HPCToolkit fails when it tries to use a version of CUPTI that is too new for the version of the driver installed. I have found that I can run CUDA 11 programs on Ascent even though there is a CUDA 10 kernel driver. However, we have seen that using a version of CUPTI newer than the kernel driver can cause problems. As a result, I recommend that we change the implementation of cupti_path in HPCToolkit to always use the CUPTI path hardcoded in the HPCToolkit build. The recommendation for users and installers is to build and install HPCToolkit for the latest version of CUDA supported by their kernel driver.

Note: I adjusted some of the text in the HPCToolkit manual troubleshooting guide to clarify this guidance.

FYI: In some experiments on Ascent yesterday, I think that the path constructed for the baked in CUPTI is missing a slash. We never noticed because HPCToolkit always ended up using the one it computed dynamically from the version of CUDA used.

**Comment by Jokeren** [comment]
Interesting. Can you please check in this fix? I would like to see if it fixes all compatibility problems.

**Comment by jmellorcrummey** [comment]
I haven't completed it. I can finish this after class.

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/375)
