### ISSUE TITLE
Disallow multiple GPU profiling options at runtime

### ISSUE THREAD

**Issue by martyitz** [HPCToolkit/hpctoolkit#381]
The options are effectively mutually exclusive, and hpcrun should detect and report the incompatibility

**Comment by Jokeren** [comment]
It will be fixed in the new cupti branch, which is not yet public.

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/381)
