### ISSUE TITLE
Under some circumstances, hpcrun fails to measure using Linux perf

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpctoolkit#383]
On Sandia's eclipse, hpcrun fails to measure perf metrics (e.g., cycles, instructions) using HPCToolkit's perf sample source. 

`perf record -e cycles app`

also fails to record samples on eclipse. Both hpcrun and perf record work on ghost.

`hpcrun -e PAPI_TOT_CYC app`

works on eclipse.

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/383)
