### ISSUE TITLE
Large overhead (>1000%) in ARM single-node executions with MPI

### ISSUE THREAD

**Issue by gagiuntoli** [HPCToolkit/hpctoolkit#387]
Info:
- Architecture: ARM
- HPCToolkit installed with Spack 0.16.0 & gcc 7.5.0

I am experiencing a large overhead (>1000%) when I execute gromacs-2021 or any other MPI (OpenMPI) application with `hpcrun` in an ARM server.

      mpirun -np 48 hpcrun -e CPUTIME ./bin/gmx_mpi <args>

With OpenMP or single-thread applications, HPCToolkit works fine. The same programs in x86 using the same version of HPCToolkit and run with MPI work fine (without that huge overhead).

**Comment by gagiuntoli** [comment]
I found that the problem in the ARM server doesn't persist if I use the OpenMPI version installed by Spack. In x86 I don't have that overhead when I use other OpenMPI version independent from Spack.

**Comment by gagiuntoli** [comment]
I found that the problem in the ARM server doesn't persist if I use the OpenMPI version installed by Spack. In x86 I don't have that overhead when I use other OpenMPI version independent from Spack.

**Comment by jmellorcrummey** [comment]
@mwkrentel this might be because your default openmpi uses UCX, which hijacks mmap, which is used by hpctoolkit. we fixed this in master and are on the verge of qualifying a new release.
