### ISSUE TITLE
kernel device drivers are loaded at different offsets into the kernel address space on different nodes

### ISSUE THREAD

**Issue by laksono** [HPCToolkit/hpctoolkit#39]
It turns out that when measuring applications using kernel sampling on more than one node, kernel device drivers are loaded at different offsets into the kernel address space on different nodes. Thus, to properly interpret kernel samples on a collection of nodes, it is critical to record the kernel map from /proc/kallsyms on each node.

**Comment by jmellorcrummey** [comment]
Merged into master with commit 20375ab
