### ISSUE TITLE
Monitor CUDA Memset, MemAlloc, and MemFree in HPCToolkit

### ISSUE THREAD

**Issue by Jokeren** [HPCToolkit/hpctoolkit#393]
All these activities now have a correlationId ready such that we can correlate them with CPU calling context.

Memory alloc/free:

https://docs.nvidia.com/cupti/Cupti/annotated.html#structCUpti__ActivityMemory2

Memoy set:

https://docs.nvidia.com/cupti/Cupti/annotated.html#structCUpti__ActivityMemset3

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/393)
