### ISSUE TITLE
CUPTI Support Compatibility Check

### ISSUE THREAD

**Issue by Jokeren** [HPCToolkit/hpctoolkit#394]
There are quite a bunch of new activity introduced in CUDA-11.2. Presumably, even more will be brought in CUDA-11.3 in the next month.

When we implement features based on these new activities, we should be careful about the minimum supported CUPTI version. For example, `CUpti_ActivityMemoryPool` is a new feature only collected in CUDA-11.2.

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/394)
