### ISSUE TITLE
Visualize unified memory activities in trace view

### ISSUE THREAD

**Issue by Jokeren** [HPCToolkit/hpctoolkit#396]
Right now, we don't turn on unified profiling because we cannot attribute a unified memory activities to its call stack. Since some users think it is worthwhile to have it shown on the trace view, we shall have a plan to implement this feature.

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/396)
