### ISSUE TITLE
hpcstruct -o out.db measurements-directory ignores -o option

### ISSUE THREAD

**Issue by martyitz** [HPCToolkit/hpctoolkit#398]
It should emit a comment to that effect so that the user understands not to use -o when processing
a measurements directory

**Comment by martyitz** [comment]
-o is being removed

**Comment by martyitz** [comment]
-o is not being removed; it will just be referred to as applicable only for single binaries.

**Comment by martyitz** [comment]
-o should generate a warning message that it is ignored when hpcstruct is invoked on a measurements directory.

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/398)
