### ISSUE TITLE
I got an error when I ran “make install”

### ISSUE THREAD

**Issue by sunnchioo** [HPCToolkit/hpctoolkit#401]
collect2: error: ld returned 1 exit status
Makefile:727: recipe for target 'hpcstruct-bin' failed
make[4]: *** [hpcstruct-bin] Error 1
make[4]: Leaving directory '/home/syt/GVProf/hpctoolkit/build/src/tool/hpcstruct'
Makefile:970: recipe for target 'install' failed
make[3]: *** [install] Error 2
make[3]: Leaving directory '/home/syt/GVProf/hpctoolkit/build/src/tool/hpcstruct'
Makefile:523: recipe for target 'install-recursive' failed
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory '/home/syt/GVProf/hpctoolkit/build/src/tool'
Makefile:508: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/home/syt/GVProf/hpctoolkit/build/src'
Makefile:652: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

**Comment by jmellorcrummey** [comment]
that is not a useful error report. post your config.log.

**Comment by sunnchioo** [comment]
> that is not a useful error report. post your config.log.
> 
> what branch are you building?

Hello.

I created a folder “build” and ran this code

 `../configure --prefix=/home/syt/GVProf/hpctoolkit/installation --with-cuda=/usr/local/cuda-11.0 --with-sanitizer=/usr/local/cuda-11.0/Sanitizer --with-gpu-patch=/home/syt/GVProf/gpu-patch/installation --with-redshow=/home/syt/GVProf/redshow/installation --with-spack=/home/syt/GVProf/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.5.0/`

It created file "config.log" https://github.com/sunnchioo/About_GVProf/blob/main/config.log

Then  I ran `make install`, but I got an error. 

And there is no folder “installaton” in `/hpctoolkit`.

**Comment by jmellorcrummey** [comment]
one problem is that you are missing dependencies that should be installed with spack:

configure:27220:   libiberty:    no
configure:27222:   libmonitor:   /home/syt/GVProf/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.5.0/libmonitor-2020.10.15-ftbgxilfojjgeq2ek7cu3gnwzgv7wckk
configure:27224:   libunwind:    /home/syt/GVProf/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.5.0/libunwind-1.5.0-sjylcwwe2hjvt3sjktcufqqk25y35auo
configure:27226:   lzma:         /home/syt/GVProf/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.5.0/xz-5.2.5-w77dyxcueztmpo7scmhidybrjfsa4eiz
configure:27228:   mbedtls:      /home/syt/GVProf/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.5.0/mbedtls-2.16.9-bxhzs73pfh2wwntzl4eynm5nai4cfatp
configure:27230:   papi:         no
configure:27232:   perfmon:      no
configure:27234:   tbb:          /home/syt/GVProf/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.5.0/intel-tbb-2020.3-jg6xrffzcjl46bxzhrog4ocdn2i252cd
configure:27236:   xed:          no

if you use

spack install —only dependencies hpctoolkit

you should get the missing dependencies. note that you need either perfmon or papi, not both.

spack will attempt to install papi. if that doesn’t work, you can rerun the command above with -papi and it will install perfmon instead.

**Comment by Jokeren** [comment]
Thank you @jmellorcrummey . I believe this is more of a GVProf issue.

@sunnchioo 

Some packages like intel-xed are not correctly installed with spack. Maybe you want to try `spack install intel-xed@12.0.1` first and see the error message.

Note that cuda-11.0 does not quite work with the current gvprof master. Can you please try cuda-11.2?

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/401)
