### ISSUE TITLE
Current master branch cannot profile Firefox

### ISSUE THREAD

**Issue by mxz297** [HPCToolkit/hpctoolkit#402]
I build latest master branch (without any GPU support) and try to run it with Firefox. I did the experiment on gpu.cs.rice.edu.  I ran it with `hpcrun -e cycles firefox`. `firefox` is a shell script which will eventually launch a  browser window. The Firefox window cannot load any webpage and says "Restart Required"

![image](https://user-images.githubusercontent.com/1683713/116174434-014c7e80-a6d4-11eb-9c24-d5f247da0224.png)

This is a situation where hpcrun breaks the behavior of the application. Firefox is extremely complicated software, so I am surprised that things do not work out-of-box. Based the error messages on the terminal, there seems to be two issues:

1. There seems to be file descriptor conflicts between hpcrun and Firefox:
```
monitor warning [33170,121] monitor_thread_shootdown: timeout exceeded (10): unable to deliver monitor_fini_thread() to 114 threads
hpctoolkit warning: unable to access log file (maybe application closed the file descriptor)
monitor warning [33340,121] monitor_thread_shootdown: timeout exceeded (10): unable to deliver monitor_fini_thread() to 71 threads
hpctoolkit warning: unable to access log file (maybe application closed the file descriptor)

hpctoolkit warning: unable to access log file (maybe application closed the file descriptor)
hpctoolkit: unable to open hpcrun file: '/home/xm13/projects/test/hpctoolkit-firefox-measurements/firefox-000000-001-2a805680-32935-0.hpcrun': File exists
```

2. hpcrun seems to affect `epoll` as Firefox complains:
```
[warn] Epoll ADD(1) on fd 3 failed. Old events were 0; read change was 1 (add); write change was 0 (none); close change was 0 (none): Operation not permitted
```

Are we currently do anything to prevent applications to close log, profile, and trace files?

This issue is definitely not a release blocker, but it would be nice to be able to profile complicated code.

**Comment by jmellorcrummey** [comment]
The problem seems to be caused by calls to close EVERY file, not just ones Firefox opened in the destructor in the following code. https://chromium.googlesource.com/chromium/src/+/39.0.2171.99/ipc/file_descriptor_set_posix.cc. 

I think the only way we can get around this is to wrap close and not let it close our files.

Given the error report at the end of Xiaozhu's entry, it seems that we either need to make changes for epoll as well.

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/402)
