### ISSUE TITLE
hpcprof gets confused when the measurements directory contains data from multiple programs

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpctoolkit#409]
Running an program on Summit, which called system, which apparently invoked mkdir caused a measurements directory to have profiles and traces for:
- the application
- mkdir
- bash
Hpcprof reported lots of conflicting CPIDs during analysis. it is unclear whether hpcprof produced trace or not. in any case, trace data could not be viewed by hpcviewer.

after removing the measurement files for bash and mkdir, the situation improved. 

we need to make sure that prof2 deals with this case better. we need to create a test case.

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/409)
