### ISSUE TITLE
Line map bug on P8/LE

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpctoolkit#41]
Hpcstruct can’t read the line map from binaries generate by IBM XL compilers at present. The version of libdwarf used by hpcstruct and Dyninst in HPCtoolkit doesn’t interpret the line map correctly. Libdw does understand maps produced by XL compilers. Plan: switch to newer Dyninst based on libdw.

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/41)
