### ISSUE TITLE
hpcrun exited early when profiling Apache HTTP server

### ISSUE THREAD

**Issue by mxz297** [HPCToolkit/hpctoolkit#410]
`httpd` (the main executable of the Apache HTTP server) by default will fork several processes to run its HTTP service as daemon processes. When running `hprun ./httpd`, there will be no daemon processes running in the background. Error log from httpd contains:

`hpcrun: could not create output directory `./hpctoolkit-httpd-measurements': Permission denied`

Through gdb, I found that after the first fork of `httpd`, the child process attempts to call `mkdir` to create the measurement directory and gets the error. 

I tried to explore this issue a little bit, but cannot find what's the root cause of the permission issue:

1. the uid, euid, gid, eguid of the child process is the same as the parent process when the child process calls mkdir.
2. the child process can actually call `fopen` to create and write a file inside `./hpctoolkit-httpd-measurements`.

**Comment by mxz297** [comment]
To reproduce, on ufront, after `hpcrun /home/xm13/projects/HTTPD/install/bin/httpd`, `killall -9 httpd` should print no error. Currently, `killall -9 httpd` prints `httpd: no process found` as under hpcrun, httpd's daemon processes exited.

**Comment by jmellorcrummey** [comment]
> hpcrun: could not create output directory ./hpctoolkit-httpd-measurements': Permission denied`
> 
> Through gdb, I found that after the first fork of httpd, the child process attempts to call mkdir to create the measurement directory and gets the error. 

My guess is that the directory is already created by the parent process, so the child process fails with the create. Perhaps we should consider creating the directory with the suffix "-<processid>"? We need to be careful with MPI processes that need to write data to the same directory. We don't want multiple directories created.

**Comment by mxz297** [comment]
@jmellorcrummey Our code actually ignores error `EEXIST`: https://github.com/HPCToolkit/hpctoolkit/blob/master/src/tool/hpcrun/files.c#L404

**Comment by jmellorcrummey** [comment]
I am puzzled because you've already stated that user and group permissions seem the same. Is it possible that the http daemon is using capabilities https://man7.org/linux/man-pages/man7/capabilities.7.html ?

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/410)
