### ISSUE TITLE
Installation without internet connection 

### ISSUE THREAD

**Issue by lcebaman** [HPCToolkit/hpctoolkit#427]
Hello,

I was wondering if there is a way to install it without sudo and internet access. On the machine I would like to install it I do not have Spack, outside world connection or sudo access. Is there a way to install it as it was before?

**Comment by mwkrentel** [comment]
@lcebaman Yes, we are no longer an isolated project, we're now part of
ECP, the Exa-Scale Computing Project.  As such, we build hpctoolkit
plus all the prereqs via spack.

For your case, not connected to the internet, spack has a feature
called a "mirror."  Basically, you start on a machine that does have
internet access and tell spack to download all the tarfiles and put
them in the mirror.  Then put spack and the mirror on a DVD or
something.

https://spack.readthedocs.io/en/latest/mirrors.html

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/427)
