### ISSUE TITLE
Implement inlined file contexts

### ISSUE THREAD

**Issue by blue42u** [HPCToolkit/hpctoolkit#438]
#### Background/Specification
Before 11.2, CUDA's NVCC does not emit debugging information on inlined function calls, which complicates analysis of applications with large numbers of inlined templates. In this case the best possible result is provided by the `<inlined from x.cu>` contexts, which are based on the files listed in the line map for various instructions. Currently Prof2 will never emit an `<inlined from>` context, to avoid the addition of annoying "fluff" contexts in heavily optimized C++ code (e.g. where the file chosen by Struct for the caller function is incorrect, for instance with inlined constructors).

While it is straightforward to implement the `<inlined from>` contexts in Prof2 (they are simply a new `Scope::Type`), I would like these to be limited only to the cases where they are necessary, cases where it is known that inlining information is not available. This would have to be determined in Struct by some means (e.g. checking if the line map is NVIDIA's extended version or not) and then flagged in the Structfile, which would then slightly alter the conversion done by `finalizers::StructFile`.

#### Action items
 - [ ] Implement a test in `hpcstruct` for pre-11.2 CUDA binaries, and output its result in the Structfile (e.g. attribute on `<LM>`).
 - [ ] Extend `Scope` to support `<inlined from>` contexts (say `inlined_file`).
 - [ ] Extend `sinks::ExperimentXML4` to support the new Scope (which should be output as a single-alien tag).
 - [ ] Adjust `finalizers::StructFile` to interpret `<F>` tags as `inlined_file` Scopes if the the Structfile is marked for pre-11.2 CUDA.

**Comment by Jokeren** [comment]
This one would be low priority as we are moving forward to employ the new format.

**Comment by blue42u** [comment]
I'm good with deprioritizing this front if we don't have a pressing need to support older CUDAs, if @jmellorcrummey would be willing to confirm this.

**Comment by jmellorcrummey** [comment]
I am fine with deprioritizing older CUDA. People should be moving to the new CUDA, though Sandia has not. They are still using 10.1.243 and 10.2.89

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/438)
