### ISSUE TITLE
Refine the GPU CCT reconstruction bits.

### ISSUE THREAD

**Issue by Jokeren** [HPCToolkit/hpctoolkit#440]
While I think they work just fine, I don't actually have the proper test cases or knowledge to know whether they are complete. I could use some confirmation they are sufficient and complete for all the crazy reconstructions we do.

They probably also need some code cleanup.

#### Action items
 - [ ] Properly document the non-standard Context classes and `Metric::*finalize`, so someone other than me (@blue42u) can actually understand what's going on.
 - [ ] (If needed) refactor CollaborativeContexts to use clean C++ instead of whatever mess it is currently.

**Comment by Jokeren** [comment]
@blue42u check out test cases prefixed by `cu_call_path`. 
https://github.com/Jokeren/hpctoolkit-gpu-samples

**Comment by blue42u** [comment]
@Jokeren I know those exist (and remember experimenting with a few when I wrote the pieces originally), but I have no idea what they're supposed to look like in the final database. I could compare with the current output from `master` but I don't understand the algorithm well enough to know what an acceptable error bound is, nor what I'm looking for to test the edge cases (e.g. all-zeros distribution). And its unclear to me whether any of these can test the infrastructure for range-based sampling, which I'm less confident in.

So, if you could, I would appreciate it if you test the current Prof2 and let me know how it fares. That request extends to the Intel and AMD support projects as well (@aarontcopal2, @dejangrubisic and @mxz297 I think?), I really just need more information on what Prof2 needs to provide to support everyone's GPU work for this front.

**Comment by Jokeren** [comment]
Those tests do not cover range-based sampling because they only have a single GPU kernel. I'll try the current prof2 first and see if it works

**Comment by Jokeren** [comment]
Actually, if hpcstruct could mark the GPU structure file as `without cfg`, I feel like hpcprof2's check could be simplified.

**Comment by blue42u** [comment]
(For context, me and Keren debugged his issue and found it was a pilot error, he forgot the `--gpucfg yes`.)

@Jokeren You've got the right idea, the marker needs to be a tristate though (`--gpucfg no`, `--gpucfg yes` and not a GPU binary or a GPU binary without Dyninst support). The other factor is that if you've measured with `-e gpu=nvidia` you can't use CFG data anyway so we shouldn't suggest it. I currently can't think of an (agnostic) way to detect that easily, it would help if the CCT used to mark the kernel function in Run was marked as a "function-level CCT" (as opposed to the usual instruction-level CCTs).
