### ISSUE TITLE
Hpcrun hangs at exit with older Glibc

### ISSUE THREAD

**Issue by blue42u** [HPCToolkit/hpctoolkit#455]
Title says it all. Observed in `master`.

~~It appears the OpenMP threads are simply waiting around during the shootdown, the shootdown signal seems not to be delivered to these threads. Still investigating if the cause is an unknown modification to the signal disposition(s).~~

~~May have some interaction with #423.~~

**UPDATE:** I've figured out the issue, the OpenMP is really a red herring (easiest way to trigger the issue, but not actually the cause). In order:
1. The Fnbounds server is launched through a pair of calls to clone(). The clone() function is actually a Glibc wrapper around the clone syscall, the wrapper adds some code into the child to reset bits to make sure pthreads work properly. For obvious reasons its sensitive to whether the clone() is a "thread-like" or a "process-like".
2. Later, an OpenMP implementation spawns a thread team. Nothing special here, libmonitor tracks all the threads like it should.
3. When the application exits, libmonitor finalizes before OpenMP so the threads are still alive. This is a normal case, and causes libmonitor to decide to start the shootdown.
4. As part of the shootdown, libmonitor uses pthread_kill to send the shootdown signal to make the threads drain as they should. But the threads never get the signal.

Now for the chaotic chain of causes:
- The pthread_kill in (4) is actually throwing an error, but libmonitor pays no heed and stubbornly keeps trying without making any visible progress.
- The pthread_kill fails because its internal syscall to tgkill fails. tgkill takes both the pid and tid of the target (as a way to make sure the tid didn't get reused over process boundaries), in this case the pid is incorrectly -1.
- The reason the pid is -1 is because the Glibc internal pthreads state was reset, by the Glibc wrapper in the child process, through the shared CLONE_VM memory space, from (1).
- ...And this is a bug in Glibc, which was fixed in 2.24 (https://sourceware.org/bugzilla/show_bug.cgi?id=19957). NOTS and llnl.cs both run 2.17, and if my theory is sound this should also show up on gpu.cs.

Based on the bug reports a bunch of things go wrong when the pthread state is randomly reset. To be honest I'm surprised there weren't more mysterious crashes.

**Comment by jmellorcrummey** [comment]
I don't think this has anything to do with #452 because I see the problem at commit 312fad210b377dd5206b6641d71a2fd99682a4cf

**Comment by blue42u** [comment]
Updated OP with my latest findings (copied from Slack).

If we attempt a fix, it will be hacky and might not work in all cases. I happen to have stumbled across one, if the body of the child never returns back to the Glibc wrapper the reset doesn't happen, so if the child dies by signal it all magically works (the grandchild exec's anyway so it isn't affected).

The other option is to do nothing and explicitly drop support for Glibc older than 2.24, which is already 5 years old. 2.28 is in RHEL 8, which most everyone is using now. If we want to use LD_AUDIT extensively we'll need new Glibc anyway.
