### ISSUE TITLE
Suppressed threads have memory leaking issues

### ISSUE THREAD

**Issue by Jokeren** [HPCToolkit/hpctoolkit#462]
https://github.com/HPCToolkit/hpctoolkit/blob/f1236e3521ca743f5d69bc878dbf0906df0a897f/src/tool/hpcrun/main.c#L778

When `demand_new_thread = true`, `hpcrun_threadMgr_data_get_safe` will allocate a new piece of data instead of using the existing ones in the memory pool. 

https://github.com/HPCToolkit/hpctoolkit/blob/f1236e3521ca743f5d69bc878dbf0906df0a897f/src/tool/hpcrun/main.c#L822

Then, in `hpcrun_thread_fini`, we don't call `hpcrun_threadMgr_data_put` to recycle the current thread's thread data. Thereby, a thread is both _suppressed_ and _demanding new thread data_ has the memory leak issue. This is benign usually. However, if an application creates thousands of threads, hpcrun will allocate a tens of gigabytes of CPU memory, causing an **serious problem**.

I observed this problem when monitoring laghos using the continuous pc sampling feature, which creates a helper thread at every `pcSamplingStart` call, and the thread is terminated at every `pcSampingStop` call. Since the helper threads are very lightweight, themselves do not cause performance issues. The real problem is that hpcrun allocates thread data but doesn't recycle it so that the memory usage is exploded from 1.9GB to 12GB within just 12 secs. If we ran Laghos for 10 minutes, it could consume ~600GB memory!

**Comment by blue42u** [comment]
@Jokeren Is this not an observable issue now? I thought we still needed another patch making use of https://github.com/HPCToolkit/libmonitor/pull/2.

**Comment by Jokeren** [comment]
@blue42u This patch in hpcrun could fix the problem, while the monitor change could make hpcrun even better by completely ignoring threads being monitored.

**Comment by Jokeren** [comment]
@blue42u You are right. I also need libmonitor's support to get this problem fixed. Moreover, merging develop caused a bunch of other problems.

**Comment by Jokeren** [comment]
#473 needs to be revised.
