### ISSUE TITLE
Clean up thread_data_t

### ISSUE THREAD

**Issue by Jokeren** [HPCToolkit/hpctoolkit#464]
There are may staled/unused fields (e.g., add_to_pool, defer_write) in `thread_data_t`. It would be better if we can take out those fields to prevent `thread_data` keep growing. 

https://github.com/HPCToolkit/hpctoolkit/blob/f1236e3521ca743f5d69bc878dbf0906df0a897f/src/tool/hpcrun/thread_data.h#L140

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/464)
