### ISSUE TITLE
Develop branch failed to parse CPU struct files in the measurement directory

### ISSUE THREAD

**Issue by Jokeren** [HPCToolkit/hpctoolkit#474]
With @jmellorcrummey 's update, CPU structure files are also generated under `<measurement-dir>/<structs>`. It appears to me that hpcprof2 might consider all the files in  `<measurement-dir>/<structs>` are GPU struct files so it outputs an error `ERROR: Error while parsing Structfile Makefile`.

Do you have any idea to fix this problem? @blue42u

**Comment by blue42u** [comment]
Ugh. As clever as it is I hate that we're using `make` to do this.

Technically a harmless error, but hotpatched in `develop`.
