### ISSUE TITLE
Handling metrics with procentage (rather than count)

### ISSUE THREAD

**Issue by dejangrubisic** [HPCToolkit/hpctoolkit#476]
All metrics are summing up to 100% which allows the user to see where the metric count is the highest. Although some metrics like GPU_BUSY show the percentage of GPU usage for a given kernel invocation. This will need to have a different mechanism, since summing percentages across whole execution doesn't make much sense.

Using some kind of DIVISION_FORMULA(GPU_KINFO_STMEM); from gpu-metrics.c would make sense

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/476)
