### ISSUE TITLE
Cleanning up and defining the structure for the formats (hpcrun, hpcprof)

### ISSUE THREAD

**Issue by dejangrubisic** [HPCToolkit/hpctoolkit#478]
Organize all formats in the separate files, and define the interface each format has to have. Currently, formats are predominantly implemented in hpcrun-fmt.c that has more than 2k lines. I suggest we define folders:
src/lib/prof-lean/hpcrun-formats/
src/lib/prof-lean/hpcprof-formats/

and each having independent structures for formats. The naming scheme is also not consistent and needs to be defined and implemented.

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/478)
