### ISSUE TITLE
Need to replace fixed-size event array with a list

### ISSUE THREAD

**Issue by laksono** [HPCToolkit/hpctoolkit#48]
Currently we limit the number of events to be 50 as defined in evlist.h:
```C
#define MAX_EVENTS  50 
...
typedef struct evlist_t {
  char evl_spec[MAX_EVL_SIZE];
  int nevents;
  _ev_t events[MAX_EVENTS];
} evlist_t;
```
It's better to have a more flexible data structure such as linked list so that the number can exceed the limitation.

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/48)
