### ISSUE TITLE
One command for hpcrun + hpcstruct + prof2-mpi

### ISSUE THREAD

**Issue by dejangrubisic** [HPCToolkit/hpctoolkit#480]
This is one topic we discussed in one of our meetings. I think it would be useful for some users in national labs to have one command that launches hpctoolkit and outputs a database directory. The motivation for this is:

1. To lower the time of hpctoolkit profiling (the user currently needs to wait two times to get queue, once for hpcrun and once for prof2-mpi)
2. To lower the complexity and space for errors (run just one default command instead of three)

The idea is that once we get queue:

1. Run hpcrun with user arguments
2. Check the output  of hpcrun (if bad return)
3. Run hpcstruct on binary | Run hpcstruct on measurements 
4. Run prof2-mpi (on given nodes)

I am aware that the optimal number of nodes for prof2-mpi is not necessarily the number of nodes for the application, but the argument is that a smaller run will create less profiling data and prof2-mpi will be fine with less nodes. If the run use many nodes, we will collect much more data and prof2-mpi will be fine with more nodes.

This command will not replace hpcrun, hpcstruct or hpcprof2-mpi, but will be just an addition that users can call independently.

**Comment by Jokeren** [comment]
@martyitz Actually Dejan posted this request long time ago.

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/480)
