### ISSUE TITLE
Traceview doesn't present different kernel names when called in sequence from array of kernel pointers

### ISSUE THREAD

**Issue by dejangrubisic** [HPCToolkit/hpctoolkit#490]
If nvidia gpu code looks like:
...
  cu_load_module_function(moduleAdd, "vecAdd.cubin", vecAdd, "vecAdd");
  cu_load_module_function(moduleSub, "vecSub.cubin", vecSub, "vecSub");
...
  CUfunction funcs[] = {vecAdd, vecSub};
...
  GPU_TEST_FOR(DRIVER_API_CALL(cuLaunchKernel(funcs[i % 2], blocks, 1, 1, threads, 1, 1, 0, 0, args, 0)));

  GPU_TEST_FOR(DRIVER_API_CALL(cuLaunchKernel(vecAdd, blocks, 1, 1, threads, 1, 1, 0, 0, args, 0)));
  GPU_TEST_FOR(DRIVER_API_CALL(cuLaunchKernel(vecSub, blocks, 1, 1, threads, 1, 1, 0, 0, args, 0)));
...
Traceview looks like:
![image](https://user-images.githubusercontent.com/40608743/144684252-bd82ca25-2b19-4dc2-a21b-2b82abaf059f.png)
Here we can see that the first 2/3 are vecAdd and the last 1/3 is vecSub. Correct would be that the first 1/3 has both kernels.

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/490)
