### ISSUE TITLE
don't flush GPU records on a thread that hasn't performed any GPU operations

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpctoolkit#494]
Flushing GPU records by calling routines such cuptiActivityFlush  and ompt_trace_flush has caused problems when HPCToolkit's monitoring has been turned on for certain threads. 

To address this issue, I propose we add a tracking mechanism for each of the flavors of GPU events we might flush:
CUDA
ROCM
OMPT

I think that HPCToolkit already has an accounting mechanism for OpenCL and Level 0 to make sure that completion events match the number of submitted operations.

For each of CUDA, ROCM, and OMPT, we need only maintain a boolean that indicates that an operation has been submitted since the last flush. When calling a flush operation for each of these GPU operation classes, only perform the flush if the flag is set and then clear the flag. The flag should be thread-local.

**Comment by jmellorcrummey** [comment]
fixed for AMD OMPT in 3d9994a809

**Comment by Jokeren** [comment]
We do have a flag for CUPTI.

https://github.com/HPCToolkit/hpctoolkit/blob/e06dd3496e2f9b6f6d63882efe159c7ec177b077/src/tool/hpcrun/gpu/nvidia/cupti-api.c#L1610

**Comment by jmellorcrummey** [comment]
@Jokeren thanks for pointing out that we do have such a flag for CUPTI. we should name them consistently across the GPU instrastructures.
