### ISSUE TITLE
Not able to install hpctoolkit with Intel Compiler using spack

### ISSUE THREAD

**Issue by mohit9638iitk** [HPCToolkit/hpctoolkit#498]
Output of compilers.yaml

compilers:

    compiler:
    paths:
    cc: /usr/bin/gcc
    cxx: /usr/bin/g++
    f77: /usr/bin/gfortran
    fc: /usr/bin/gfortran
    operating_system: centos7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: gcc@4.8.5
    compiler:
    paths:
    cc: /home/apps/cdac/gcc/8.3.0/bin/gcc
    cxx: /home/apps/cdac/gcc/8.3.0/bin/g++
    f77: /home/apps/cdac/gcc/8.3.0/bin/gfortran
    fc: /home/apps/cdac/gcc/8.3.0/bin/gfortran
    operating_system: centos7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: gcc@8.3.0
    compiler:
    paths:
    cc: /opt/ohpc/pub/apps/intel/2018/compilers_and_libraries_2018.5.274/linux/bin/intel64/icc
    cxx: /opt/ohpc/pub/apps/intel/2018/compilers_and_libraries_2018.5.274/linux/bin/intel64/icpc
    f77: /opt/ohpc/pub/apps/intel/2018/compilers_and_libraries_2018.5.274/linux/bin/intel64/ifort
    fc: /opt/ohpc/pub/apps/intel/2018/compilers_and_libraries_2018.5.274/linux/bin/intel64/ifort
    operating_system: centos7
    target: x86_64
    modules: []
    environment:
    set:
    LD_LIBRARY_PATH : /home/apps/cdac/gcc/8.3.0/lib64:/opt/intel/compilers_and_libraries_2018.5.274/linux/mpi/intel64/lib
    extra_rpaths:
    - /opt/intel/compilers_and_libraries_2018.5.274/linux/mpi/intel64/lib
    - /home/apps/cdac/gcc/8.3.0/lib64
    - /usr/local/lib64
    flags: {}
    spec: intel@18.0.5

I am trying to build hpctoolkit with intel compiler using spack with following command:-

spack install --only dependencies hpctoolkit %intel@18.0.5

It is showing error in dependencies "m4-1.4.19-bbvsx5nrssevyt2vxdxeyapq37jpjgdi"

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for gcc... /home/mohitkumar20/spack/lib/spack/env/intel/icc
checking whether the C compiler works... no
configure: error: in `/tmp/mohitkumar20/spack-stage/spack-stage-m4-1.4.19-rl5r7qkcwxawxpxwqaqrnabi5nhg77zf/spack-src/spack-build':
configure: error: C compiler cannot create executables

Please someone help me regarding this.

**Comment by jmellorcrummey** [comment]
We never install HPCToolkit with anything other than the GNU compilers. From your file above, you should use gcc 8.3.0.

If you build HPCToolkit with GNU compilers, you can use it to measure applications built with Intel compilers. There is no need to build it with Intel compilers.

**Comment by mohit9638iitk** [comment]
Thanks @jmellorcrummey for clarification.
