### ISSUE TITLE
Not able to compile statically if using intel compiler instead of mpich(mpicc).

### ISSUE THREAD

**Issue by mohit9638iitk** [HPCToolkit/hpctoolkit#499]
I am able to compile my code with mpicc(mpich implementation) with hpclink:

$ hpclink mpicc -static -g mpi_3d_fftw.cpp mylib.o -o fftw_non_block -lfftw3_mpi -lfftw3 -lblitz -lm

But when changes to intel compiler e.g mpiicpc , it shows error .

$ hpclink mpiicpc -static -g mpi_3d_fftw.cpp mylib.o -o fftw_non_block -lfftw3_mpi -lfftw3 -lblitz -lm

Error:-

hpclink: preliminary link 1 ...
hpclink: unable to link

mpiicpc -Wl,--wrap=poll -Wl,--wrap=select -Wl,--wrap=ppoll -Wl,--wrap=pselect -Wl,--wrap=execl -Wl,--wrap=execle -Wl,--wrap=execlp -Wl,--wrap=execv -Wl,--wrap=execve -Wl,--wrap=execvp -Wl,--wrap=fork -Wl,--wrap=system -Wl,--wrap=vfork -Wl,--wrap=sigaction -Wl,--wrap=signal -Wl,--wrap=sigprocmask -Wl,--wrap=MPI_Init -Wl,--wrap=MPI_Init_thread -Wl,--wrap=MPI_Finalize -Wl,--wrap=MPI_Comm_rank -Wl,--wrap=mpi_init -Wl,--wrap=mpi_init_thread -Wl,--wrap=mpi_finalize -Wl,--wrap=mpi_comm_rank -Wl,--wrap=mpi_init_ -Wl,--wrap=mpi_init_thread_ -Wl,--wrap=mpi_finalize_ -Wl,--wrap=mpi_comm_rank_ -Wl,--wrap=mpi_init__ -Wl,--wrap=mpi_init_thread__ -Wl,--wrap=mpi_finalize__ -Wl,--wrap=mpi_comm_rank__ -Wl,--wrap=_Exit -Wl,--wrap=_exit -Wl,--wrap=exit -Wl,--wrap=main -Wl,--wrap=pthread_create -Wl,--wrap=pthread_exit -Wl,--wrap=pthread_sigmask -Wl,--wrap=sigtimedwait -Wl,--wrap=sigwait -Wl,--wrap=sigwaitinfo /home/mohitkumar20/hpctoolkit/lib/hpctoolkit/libhpcrun.o /home/mohitkumar20/hpctoolkit/lib/hpctoolkit/ext-libs/libelf.a -static -g mpi_3d_fftw.cpp mylib.o -o test_mohit -lfftw3_mpi -lfftw3 -lblitz -lm _hpc_nm_addrs_78340.o /home/mohitkumar20/hpctoolkit/lib/hpctoolkit/libhpcrun_wrap.a /home/mohitkumar20/hpctoolkit/lib/hpctoolkit/ext-libs/libmonitor_wrap.a /home/mohitkumar20/hpctoolkit/lib/hpctoolkit/ext-libs/libz.a -ldl -lrt -lpthread -lfftw3_mpi -lfftw3 -lblitz -lm

/opt/ohpc/pub/apps/intel/2018/compilers_and_libraries_2018.5.274/linux/mpi/intel64/lib/debug_mt/libmpi.a(initthread.o): In function `MPIR_Init_thread':
/tmp/mpi.xtmpdir.7b663e0dc22b2304e487307e376dc132.17861_32e/mpi.32e.ww34.20180823/dev/x86_64/debug_mt/../../src/mpi/init/initthread.c:424: warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
ld: cannot find -lstdc++
ld: cannot find -lstdc++
/lib/../lib64/libc.a(malloc.o): In function `__libc_free':
(.text+0x6950): multiple definition of `free'
/opt/ohpc/pub/apps/intel/2018/compilers_and_libraries_2018.5.274/linux/mpi/intel64/lib/debug_mt/libmpi.a(i_rtc_hook.o):/tmp/mpi.xtmpdir.7b663e0dc22b2304e487307e376dc132.17861_32e/mpi.32e.ww34.20180823/dev/src/I_MPI/rtc/x86_64/debug_mt/../../i_rtc_hook.c:45: first defined here
/lib/../lib64/libc.a(malloc.o): In function `__libc_realloc':
(.text+0x6a20): multiple definition of `realloc'
/opt/ohpc/pub/apps/intel/2018/compilers_and_libraries_2018.5.274/linux/mpi/intel64/lib/debug_mt/libmpi.a(i_rtc_hook.o):/tmp/mpi.xtmpdir.7b663e0dc22b2304e487307e376dc132.17861_32e/mpi.32e.ww34.20180823/dev/src/I_MPI/rtc/x86_64/debug_mt/../../i_rtc_hook.c:65: first defined here
/opt/ohpc/pub/apps/intel/2018/compilers_and_libraries_2018.5.274/linux/mpi/intel64/lib/debug_mt/libmpi.a(dapl_util.o): In function `dapl_get_addr_by_host_name':
/tmp/mpi.xtmpdir.7b663e0dc22b2304e487307e376dc132.17861_32e/mpi.32e.ww34.20180823/dev/x86_64/debug_mt/../../src/mpid/ch3/channels/nemesis/netmod/dapl/dapl_util.c:191: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/opt/ohpc/pub/apps/intel/2018/compilers_and_libraries_2018.5.274/linux/mpi/intel64/lib/debug_mt/libmpi.a(tcp_init.o): In function `GetSockInterfaceAddr':
/tmp/mpi.xtmpdir.7b663e0dc22b2304e487307e376dc132.17861_32e/mpi.32e.ww34.20180823/dev/x86_64/debug_mt/../../src/mpid/ch3/channels/nemesis/netmod/tcp/tcp_init.c:862: warning: Using 'gethostbyaddr' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/opt/ohpc/pub/apps/intel/2018/compilers_and_libraries_2018.5.274/linux/mpi/intel64/lib/debug_mt/libmpi.a(simple2pmi_pmi2.o): In function `PMII_Connect_to_pm':
/tmp/mpi.xtmpdir.7b663e0dc22b2304e487307e376dc132.17861_32e/mpi.32e.ww34.20180823/dev/x86_64/debug_mt/../../src/pmi/pmi2/simple/simple2pmi.c:2429: warning: Using 'gethostbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking

hpclink: error: unable to link

Please help me in understanding how to compile statically by intel compilers.

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/499)
