### ISSUE TITLE
need to garbage collect entries in GPU splay trees

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpctoolkit#515]
Issue: 

- when a correlation flows down a correlation channel, a correlation is added to the correlation splay tree
- such correlation entries are leaked rather than freed

Approach:
- for OMPT, correlations for host-op-ids in a target region can be deleted when a target region end trace record is processed
- for CUPTI and ROCM, is there a separate id for each operation?

**Comment by Jokeren** [comment]
> for CUPTI and ROCM, is there a separate id for each operation?
Yes, except for pc samples.

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/515)
