### ISSUE TITLE
Davinci: Segmentation fault when combining hardware and software events

### ISSUE THREAD

**Issue by laksono** [HPCToolkit/hpctoolkit#53]
branch: **master**
Platform: davinci
Linux login3.davinci.rice.edu 2.6.32-642.6.2.el6.x86_64 #1 SMP Mon Oct 24 10:22:33 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-4)
model name      : Intel(R) Xeon(R) CPU           X5660  @ 2.80GHz

Profiling with multiple hardware events work fine, but **combining hardware and software events cause segmentation fault**:

/work/hpc/la5/pkgs/hpctoolkit-master/bin/hpcrun -dd LINUX_PERF -e INSTRUCTIONS -e perf::CPU-CLOCK /work/hpc/la5/pkgs/hpctoolkit-master/bin/hpcstruct /work/hpc/la5/pkgs/hpctoolkit-master/libexec/hpctoolkit/hpcstruct-bin
[13405, N]: LINUX_PERF: supports event INSTRUCTIONS
[13405, N]: LINUX_PERF: supports event perf::CPU-CLOCK
[13405, N]: LINUX_PERF: supports event INSTRUCTIONS
[13405, N]: LINUX_PERF: supports event perf::CPU-CLOCK
terminate called after throwing an instance of 'Diagnostics::FatalException'
Aborted (core dumped)

Backtrace:
```
#0  0x00002acd61e3d5db in raise () from /lib64/libpthread.so.0
#1  0x00002acd5e4e786d in monitor_signal_handler () from /work/hpc/la5/pkgs/hpctoolkit-kernel/lib/hpctoolkit/ext-libs/libmonitor.so
#2  <signal handler called>
#3  0x00002acd6207e925 in raise () from /lib64/libc.so.6
#4  0x00002acd62080105 in abort () from /lib64/libc.so.6
#5  0x00002acd6174ba5d in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib64/libstdc++.so.6
#6  0x00002acd61749be6 in ?? () from /usr/lib64/libstdc++.so.6
#7  0x00002acd61749c13 in std::terminate() () from /usr/lib64/libstdc++.so.6
#8  0x00002acd61749d0e in __cxa_throw () from /usr/lib64/libstdc++.so.6
#9  0x000000000042195f in banal_sighandler (sig=11) at ../../../../src/lib/banal/Struct-Inline.cpp:128
#10 0x00002acd5e4e7781 in monitor_signal_handler () from /work/hpc/la5/pkgs/hpctoolkit-kernel/lib/hpctoolkit/ext-libs/libmonitor.so
#11 <signal handler called>
#12 0x00007fffc25938a0 in ?? ()
#13 0x00007fffc25938a0 in ?? ()
#14 0x00007fffc25938a0 in ?? ()
#15 0x00007fffc25938a0 in ?? ()
#16 0x00007fffc25938a0 in ?? ()
```

**Comment by jmellorcrummey** [comment]
Try this on Titan

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/53)
