### ISSUE TITLE
hpcrun fails to set a CPUTIME timer for bash 4.4.23(1)-release (x86_64-suse-linux-gnu)

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpctoolkit#543]
bin% bash --version
GNU bash, version 4.4.23(1)-release (x86_64-suse-linux-gnu)

bin% ./hpcrun --version
hpcrun: A member of HPCToolkit, version 2022.01.15-master
git branch:  master at 2022-03-28 (d28a411bfe2d48f4)
spack spec:  unknown (not a spack build)

bin% ./hpcrun bash
bash: ../../../../src/tool/hpcrun/audit/auditor.c:577: mainlib_connected: Assertion `!connected && "Attempt to connect more than once?"' failed.
bash: ../../../../src/tool/hpcrun/audit/auditor.c:577: mainlib_connected: Assertion `!connected && "Attempt to connect more than once?"' failed.
... (and several more)

No .bashrc file is present.

**Comment by jmellorcrummey** [comment]
The reinitialization shown below fixed problems with itimer, which was an indication that thread_data wasn't being initialized in a forked child. 

```
void  hpcrun_prepare_measurement_subsystem(bool is_child)
 {  
+  if (is_child) {
+    // reset flags so measurement system is fully initialized in a child
+    atomic_store(&ms_init_started, 0);
+    atomic_store(&ms_init_completed, 0);
+  }
+
```

However, there is still a problem with the log file:

```
bin% ./hpcrun bash
hpctoolkit warning: unable to access log file (maybe application closed the file descriptor)

```

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/543)
