### ISSUE TITLE
Some nodes disappear when using BLOCKTIME event 

### ISSUE THREAD

**Issue by laksono** [HPCToolkit/hpctoolkit#569]
This happens when profiling with -`e BLOCKTIME` event.
The BLOCKTIME event uses perf_events' context switch to find out when the application enters the kernel and when exits. The BLOCKTIME metric then records the difference to display how long the application "stalls".

However, sometimes hpcprof eliminate kernel call paths that are associated with exclusive context switch and thus eliminate the BLOCKTIME metrics.

It is possible that hpcprof accidentally prune trees since hpcrun correctly record the call paths. Need to be investigated if this problem can be fixed with prof2.

![image](https://user-images.githubusercontent.com/8781032/164119369-38c1aab9-2ab0-44f1-8ea1-c3c64f24e619.png)

**Comment by laksono** [comment]
Fixed in release 2022.03

**Comment by jmellorcrummey** [comment]
how could this be fixed in 2022.03? we were exploring the problem after that release. did you reference the right release?

**Comment by laksono** [comment]
Oops wrong issue

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/569)
