### ISSUE TITLE
PAPI events do not handle `@f` properly

### ISSUE THREAD

**Issue by blue42u** [HPCToolkit/hpctoolkit#579]
When frequencies are passed to PAPI events (eg. `-e PAPI_TOT_CYC@f100`), they are treated as if they were normal periods. This is in stark contrast to perf events (which use a specialized sampling algorithm) and itimer events (which appear to calculate period as reciprocal frequency).

Since the units for frequencies and periods differ by multiple orders of magnitude (which can cause hangs and on some systems node crashes), PAPI events should at the very least error in this case.

**Reproducer:**
```console
$ cat main.c
int main() {
  volatile double x = 17;
  for(unsigned long i = 0; i < 1UL<<26; i++) x = x * 4 + 2;
}
$ gcc -o main main.c
$ \time ./main
0.23user 0.00system 0:00.23elapsed 100%CPU (0avgtext+0avgdata 1144maxresident)k
0inputs+8outputs (0major+75minor)pagefaults 0swaps

$ hpcrun -o m.papi@N -e PAPI_TOT_CYC@123456 ./main
$ hpcrun -o m.papi@fN -e PAPI_TOT_CYC@f123456 ./main
$ grep '^SUMMARY:' m.papi@{N,fN}/*.log
m.papi@N/main-.log:SUMMARY: samples: 8198 (recorded: 8198, blocked: 0, errant: 0, trolled: 0, yielded: 0),
m.papi@fN/main-.log:SUMMARY: samples: 8198 (recorded: 8198, blocked: 0, errant: 0, trolled: 0, yielded: 0),

$ hpcrun -o m.cycles@N -e cycles@123456 ./main
$ hpcrun -o m.cycles@fN -e cycles@f`echo 8198 / .23 | bc` ./main  # freq = 8198 samples / .23 seconds
$ grep '^SUMMARY:' m.cycles@{N,fN}/*.log
m.cycles@N/main-.log:SUMMARY: samples: 9094 (recorded: 9094, blocked: 0, errant: 0, trolled: 0, yielded: 0),
m.cycles@fN/main-.log:SUMMARY: samples: 10412 (recorded: 10412, blocked: 0, errant: 0, trolled: 0, yielded: 0),

$ # NOTE: main.mt runs main() in a thread to avoid https://github.com/HPCToolkit/hpctoolkit/issues/562
$ hpcrun -o m.time@N -e CPUTIME@123 ./main.mt
$ hpcrun -o m.time@fN -e CPUTIME@f`echo 1 / .000123 | bc` ./main.mt  # freq = 1 / 123 microseconds
$ grep '^SUMMARY:' m.time@{N,fN}/*.log
m.time@N/main.mt-.log:SUMMARY: samples: 58 (recorded: 58, blocked: 0, errant: 0, trolled: 0, yielded: 0),
m.time@fN/main.mt-.log:SUMMARY: samples: 57 (recorded: 57, blocked: 0, errant: 0, trolled: 0, yielded: 0),
```

**Comment by laksono** [comment]
@blue42u  In the manual it's written that the frequency-based sampling is only supported in perf_events sample source.
You're right: we need to display an error message.

**Comment by blue42u** [comment]
Should the manual be updated to include itimer events in frequency-based sampling? It does do (more or less) the right thing.

**Comment by blue42u** [comment]
On second thought maybe not. I think `CPUTIME@f10` currently means "sample 10 times a CPU second," not "sample CPUTIME 10 times a (real) second." The unit is different and that might make a difference for threaded applications with lots of synchronization (ie. when CPUTIME != REALTIME).

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/579)
