### ISSUE TITLE
hpctraceviewer is slow on Linux

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpctoolkit#58]
large trace files many trace lines are a problem.

**Comment by mwkrentel** [comment]
What's wrong with this bug report?

How large is large?
How many trace lines?
How did you run the viewer, on laptop, off nancy, over vnc, what?
Maybe it was just nancy with the disk full, or you're over
the 8 Gig RAM that nancy has?

Can you produce a specific database and how you ran it?

I've run large trace files, and I haven't seen a problem unless I
intentionally push the trace files to something like 50 Gig (when I
was testing the server).

**Comment by jmellorcrummey** [comment]
I showed Laksono the problem and can provide 50 traces from Dyninst for which it is slow. I should have documented further in the report. Point we’ll taken.

There seems to be a GTK substrate problem.

--
John Mellor-Crummey

(sent from my phone)

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/58)
