### ISSUE TITLE
Reduce volume of data recorded for kernel symbols

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpctoolkit#59]
Recording /proc/kallsyms is wasteful. Some ways we could reduce the data size:
- We can eliminate all symbols that are not "T" or "t". It seems that this would cut the number of entries by 61%.
```
cat /proc/kallsyms | wc
 154102  540182 6955705

cat /proc/kallsyms | grep -v " T " | grep -v " t " | wc
  95251  339969 4363162
```
The average line length of /proc/kallsyms is ~45 characters. 
- We can drop the designation of symbol type, e.g., " T ", saving roughly 7%.
- We can parse the information and encode it more compactly, e.g., expressing addresses in binary rather than in ASCII. That would reduce 16 bytes to 8, saving roughly 18%.

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/59)
