### ISSUE TITLE
Any way to get human-readable format of the performance measurements without using the gui?

### ISSUE THREAD

**Issue by NicolasWinsten** [HPCToolkit/hpctoolkit#604]
I'm really only interested in the performance monitoring part of the toolkit (I'm not interested in the source code attribution).  Basically I'd like to know if there is some option to output the data collected by `hpcrun` in a human readable format.

Any help would be appreciated

**Comment by Jokeren** [comment]
`<hpctoolkit-install-path>/libexec/hpctoolkit/hpcproftt` can be used on hpcrun files. Not sure if the output fits your need though.

**Comment by tpatki** [comment]
Hi @Jokeren : Thank you for the help. Is there any way to get the output in a CSV format from `hpcrun`, for example?

**Comment by Jokeren** [comment]
I don't think so. An alternative way to get a pretty output format is using hatchet. I'm sure Stephanie and others can provide you with more information.

https://hatchet.readthedocs.io/en/latest/analysis_examples.html#read-in-an-hpctoolkit-database

**Comment by jmellorcrummey** [comment]
@tpatki I am skeptical that you really just want the hpcrun output. it consists of a set of load modules (executable, shared libraries, gpu binaries) and a "calling context tree". In the calling context tree, the nodes represent addresses of instructions in particular load modules. each node in the calling context tree has a set of associated metrics. 

is that really the level of information you want, or do you want measurement data associated with functions and load modules (e.g. the MPI library, the OpenMP runtime)? as Keren said, you can get that printed in ASCII with HPCToolkit's hpcproftt.

**Comment by tpatki** [comment]
Thanks @jmellorcrummey and @Jokeren for the prompt replies.

We are new to HPCToolkit, and we are trying to use `hpcrun` to measure performance counters for a binary (potentially on multiple MPI processes/OpenMPthreads). Something similar to the old `papiex` which is no longer supported. One of the things we don't want to do at the moment is directly annotate the source code with something like PAPI, for example. 

We would like to be able to collect such data on several apps and use the raw sampled data from the performance counters of interest for some modeling and analysis and/or policy design, and not necessarily to identify bottlenecks through visualization. 

So far, we are trying something on the lines of: 

`hpcrun -e PAPI_TOT_CYC -e PAPI_L3_DCM ./lulesh2.0 -s 2`

This creates a per-thread (or maybe per-process, I forget) `.hpcrun` profile, which we were hoping to just parse and dump into a CSV for our own analysis in R/python. What's the best way of doing this?

**Comment by Jokeren** [comment]
Hatchet seems the right way to go IMHO
