### ISSUE TITLE
Empty call path

### ISSUE THREAD

**Issue by vincentmr** [HPCToolkit/hpctoolkit#636]
I installed `hpctoolkit@2021.03.01` with spack on a Ubuntu 22.04 workstation. For example, I wrote the following program
```
program prog


   implicit none

   integer, parameter :: dp  = selected_real_kind(15, 307)
   integer, parameter :: n = 1000
   real(dp) :: A(n,n), B(n,n), C(n,n)
   integer :: i, j, k

   call random_number(A)
   call random_number(B)

   C = 0.0_dp
   do i=1, n
      do j=1, n
         do k=1, n
            C(i,j) = C(i,j) + A(i,k) * B(k,j)
         end do
      end do
   end do

end program prog
```
and I execute hpctoolkit with the following commands
```
rm -rf hpctoolkit-*-measurements
hpcrun ./prog
hpcstruct prog.f90
hpcprof -S prog.hpcstruct -I $PWD hpctoolkit-prog-measurements
```
This works fine on several computers, but on the said workstation `hpcrun` doesn't seem to find anything for the call path, and  `hpcviewer` shows 
![Screenshot from 2022-11-14 11-38-58](https://user-images.githubusercontent.com/8711156/201715853-1ea16deb-8c1c-4ec4-8375-e9ce13bcf6b0.png)
Any idea what could be causing this?

**Comment by blue42u** [comment]
This may be [a known issue with `-e CPUTIME` (the default event) on Glibc >2.34](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/646). If this workstation runs Ubuntu 22.04 or RHEL 9 or a recent Fedora, this is likely the cause. Using `-e cycles` gives a similar metric that is unaffected by this issue.

Btw, we've migrated our active development to GitLab, new issue tracker over here: https://gitlab.com/hpctoolkit/hpctoolkit/-/issues

**Comment by vincentmr** [comment]
Got it, solved it. Thanks.
