### ISSUE TITLE
hpcrun: unable to profile with PAPI native events (perf_events disabled)

### ISSUE THREAD

**Issue by laksono** [HPCToolkit/hpctoolkit#72]
Branch: master
Platforms tested: x86 (ori and cori)
PAPI: 5.5.1.3 (also 5.5.1)
configuration:
../configure --with-externals=/global/cscratch1/sd/laksono/pkgs/externals --prefix=/global/cscratch1/sd/laksono/pkgs/hpctoolkit --enable-develop --enable-mpi --with-papi=/opt/cray/pe/papi/5.5.1.3 **--disable-perf-events** MPICXX=CC MPICC=cc HPCPROFMPI_LT_LDFLAGS=-all-static

It is impossible to profile with PAPI native events using PAPI sample source only (perf_events disabled). It works fine with PAPI preset events.

> /global/cscratch1/sd/laksono/pkgs/hpctoolkit/bin/hpcrun -L | grep perf::CYCLES

perf::CYCLES

> /global/cscratch1/sd/laksono/pkgs/hpctoolkit/bin/hpcrun -dd PAPI -e papi:perf::CYCLES /global/cscratch1/sd/laksono/pkgs/hpctoolkit/bin/hpcstruct  /global/cscratch1/sd/laksono/pkgs/hpctoolkit/libexec/hpctoolkit/hpcstruct-bin

```
[165181, N]: PAPI : supports event                                                                                                                                                        
HPCToolkit fatal error: PAPI event  is not supported on this platform.                                                                                                                    
If running a dynamically-linked program with hpcrun, use 'hpcrun -L <program>' for a list of available events.                                                                            

If running a statically-linked program built with hpclink, set HPCRUN_EVENT_LIST=LIST in your environment and
run your program to see a list of available events.                                                          

Note: Either of the aforementioned methods will exit after listing available events. Arguments to your program
will be ignored. Thus, an execution to list events can be run on a single core and it will execute for only a few
seconds. 
```

> /global/cscratch1/sd/laksono/pkgs/hpctoolkit/bin/hpcrun -dd PAPI -e perf::CYCLES /global/cscratch1/sd/laksono/pkgs/hpctoolkit/bin/hpcstruct  /global/cscratch1/sd/laksono/pkgs/hpctoolkit/libexec/hpctoolkit/hpcstruct-bin
```
[178318, N]: PAPI : supports event
HPCToolkit fatal error: PAPI event  is not supported on this platform.
If running a dynamically-linked program with hpcrun, use 'hpcrun -L <program>' for a list of available events.

If running a statically-linked program built with hpclink, set HPCRUN_EVENT_LIST=LIST in your environment and
run your program to see a list of available events.

Note: Either of the aforementioned methods will exit after listing available events. Arguments to your program
will be ignored. Thus, an execution to list events can be run on a single core and it will execute for only a few
seconds.
```

**Comment by laksono** [comment]
It works with PAPI_TOT_CYC:
> /global/cscratch1/sd/laksono/pkgs/hpctoolkit/bin/hpcrun -dd PAPI -e PAPI_TOT_CYC  /global/cscratch1/sd/laksono/pkgs/hpctoolkit/bin/hpcstruct  /global/cscratch1/sd/laksono/pkgs/hpctoolkit/libexec/hpctoolkit/hpcstruct-bin
```
[62001, N]: PAPI : supports event
[62001, N]: PAPI : supports event
...
SUMMARY: samples: 10681 (recorded: 10681, blocked: 0, errant: 0, trolled: 0, yielded: 0),
```
It profiles successfully with a normal program:
> /global/cscratch1/sd/laksono/pkgs/hpctoolkit/bin/hpcrun -dd PAPI -e papi:perf::CACHE-REFERENCES@100 -e papi:perf::CACHE-MISSES@100  ./mxm 500 500 500
```
[78107, N]: PAPI : supports event
...
SUMMARY: samples: 1634327 (recorded: 1634249, blocked: 78, errant: 4, trolled: 0, yielded: 0),
```

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/72)
