### ISSUE TITLE
hpcstruct offers less helpful output for libcuda than the simple structure without it

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpctoolkit#80]
When analyzing data from rajaperf suite on gpu.cs, I tried adding struct data for libcuda. Without the struct data, there were many lines with unknown procedures attributed to specific addresses in libcuda.so. When struct output was used for libcuda instead, the useful details (virtual address and load module) got omitted and replaced with only `<unknown procedure>`. 

There are copies of databases and measurement data in  /home/johnmc/pkgs-src/rajaperf/build_rhel_nvcc9.0_gcc4.9.3/bin that you can use for testing. For instance, interpreting the measurement data with 

`hpcprof -S raja-perf-nolibs.exe.hpcstruct  hpctoolkit-raja-perf-nolibs.exe-cupti-measurements`

is better than 

`hpcprof -S raja-perf-nolibs.exe.hpcstruct  -S libcuda.so.384.81.hpcstruct hpctoolkit-raja-perf-nolibs.exe-cupti-measurements`

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/80)
