### ISSUE TITLE
font sizes in viewer and trace viewer

### ISSUE THREAD

**Issue by mwkrentel** [HPCToolkit/hpctoolkit#86]
I've noticed a couple issues, mostly on MACOSX, related to font size
in the viewer and trace viewer.  These are relevant to displaying the
viewer on a projected screen so that everyone can read the text from a
far distance.

(1) On MACOSX, the 'A+' button increases the font size, but it doesn't
increase the height of the row.  This limits how much you can increase
the font size because the text starts getting chopped.

This works on Linux/X-windows, but not on MACOSX.

(2) Across all platforms, in the trace viewer, there doesn't seem to
be any way to increase the font size of the call stack on the right
edge of the window.

(3) This isn't font related, but on MACOSX, Command-M doesn't minimize
the window.

@laksono

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/86)
