### ISSUE TITLE
lzma.h

### ISSUE THREAD

**Issue by stevenagy** [HPCToolkit/hpctoolkit#88]
Hi,

On attempting to install I get the following error:
`compress_lzma.c:65:18: fatal error: lzma.h: No such file or directory`

I previously installed hpctoolkit-externals thinking this would install any missing dependencies. What should I do?

**Comment by laksono** [comment]
lzma.h should be in hpctoolkit externals installation directory:

```<external_directory>/lzma/include/lzma.h```

If the file exists, then it must be misconfiguration of hpctoolkit.
Can you check configure hpctoolkit with the right path to externals installation directory ? Make sure you have
```
... --with-externals=<external_directory> 
```
in your hpctoolkit configure

**Comment by jmellorcrummey** [comment]
@stevenagy  We don't get automatic notifications  when new git issues are opened. I'll see if I can figure out how to set that up. At present, a more reliable way to get questions answered is through our mailing list.

**Comment by mwkrentel** [comment]
Closing this as likely pilot error.
In general, we send config questions to hpctoolkit-forum.
