### ISSUE TITLE
Profiling C++ thread: "Unknown procedure" at the root node

### ISSUE THREAD

**Issue by laksono** [HPCToolkit/hpctoolkit#90]
Branch: master

Symptom:
I profiled parallel fibonacci c++ thread version with hpcrun from master branch without tracing, and hpcprof generated 3 root nodes: `<thread root>`, `<program root>` and `<unknown procedure> 0xbb5ce [libstdc++.so.6.0.22]` 

![image](https://user-images.githubusercontent.com/8781032/42833393-944eb832-89b9-11e8-91fa-127c6f52645f.png)

This `<unknown procedure>` root has no metrics and is located at address **0xbb5ce**. According hpcfnbounds, it’s stripped:
```
…
0xbb5b0    stripped_0xbb5b0
0xbb5c0    stripped_0xbb5c0
0xbb620    stripped_0xbb620
….
```

According to hpcviewer's CCT, pthread create is called by `<unknown_procedure>` at address **0xbb8e4**. I think this procedure should be `_ZNSt6thread15_M_start_threadES... `:
```
0xbb8d0  _ZNSt6thread15_M_start_threadESt10unique_ptrINS_6_StateESt14default_deleteIS1_EEPFvvE, _ZNSt6thread15_M_start_threadESt10unique_ptrINS_6_StateESt14default_deleteIS1_EEPFvvE
0xbb900 _ZNSt6thread20hardware_concurrencyEv, _ZNSt6thread20hardware_concurrencyEv
```

It is possible this problem occurs because stdlibc++ calls `pthread_create` by address, not by calling its name:
```
   thread(thread&& __t) noexcept
    { swap(__t); }

    template<typename _Callable, typename... _Args>
      explicit
      thread(_Callable&& __f, _Args&&... __args)
      {
#ifdef GTHR_ACTIVE_PROXY
        // Create a reference to pthread_create, not just the gthr weak symbol.
        auto __depend = reinterpret_cast<void(*)()>(&pthread_create);
#else
        auto __depend = nullptr;
#endif
        _M_start_thread(_S_make_state(
              std::__bind_simple(std::forward<_Callable>(__f),
                                 std::forward<_Args>(__args)...)),
            __depend);
      }
```

Additional info: The log file shows there's no troll nor error:
```
SAMPLE ANOMALIES: blocks: 3159 (async: 3159, dlopen: 0), errors: 0 (segv: 0, soft: 0)
SUMMARY: samples: 23206 (recorded: 20047, blocked: 3159, errant: 0, trolled: 0, yielded: 0),
```

This bug is reproducible, but still hard to isolate where the problem is.

I built the test program on ori with g++ (GCC) 6.3.1 20161221 (Red Hat 6.3.1-1)

The commands I used to profile:
```
hpcrun  -dd PROCESS -dd FINI  -e cycles -e instructions   ./fib 8 3
mpirun -np 4 hpcprof-mpi -S fib.hpcstruct  hpctoolkit-fib-measurements
```

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/90)
