### ISSUE TITLE
hpcviewer doesn't work on Ubuntu 18.04

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpctoolkit#95]
Java 10 is at least one issue. It deprecates some reflection interface used in an eclipse support library. It issues warnings, but that doesn't explain why it doesn't work.

Why it doesn't work needs a bit of investigation. We might delay work on this until we move forward to a new eclipse release.

**Comment by Rombur** [comment]
Any news/workaround on this?

**Comment by jmellorcrummey** [comment]
Laksono,

My guess is that some Java newer than Java 8 is the default Java for Ubuntu 18.04.  Can one download and use Java 8 to get hpcviewer to work on Ubuntu 18.04?

Bruno,

Moving hpctoolkit’s GUIs to native Eclipse 4 and a later version of the Eclipse toolkit should enable HPCToolkit’s GUIs to be used with Java versions newer than Java 8. There is an effort to do so this summer.
--
John Mellor-Crummey		Professor
Dept of Computer Science	Rice University
email: johnmc@rice.edu		phone: 713-348-5179

**Comment by Rombur** [comment]
@jmellorcrummey thanks. For other people encountering the same problem, I installed `openjdk-8-jdk` and then added the following lines in `hpcviewer.ini`
```
-vm
/usr/lib/jvm/java-8-openjdk-amd64/jre/bin
```

**Comment by lingda-li** [comment]
Installing `openjdk-8-jdk` does solve the problem. My experience is not to add `-vm /usr/lib/jvm/java-8-openjdk-amd64/jre/bin`

**Comment by Jokeren** [comment]
@lingda-li Thanks for your comment!

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/95)
