### ISSUE TITLE
libmonitor shouldn't deliver interrupt inside libmonitor itself

### ISSUE THREAD

**Issue by laksono** [HPCToolkit/hpctoolkit#96]
Platform: gpu and knl
Application: pyramids async 4 (from inncabs benchmark)
compiler: g++ 4.8.5 (on knl)
This happens when profiling with perf_event's CYCLES (default frequency) using fix-threads branch.
It doesn't crash often, perhaps one out of 20s.

**Problem 1**:
> As we know, we wrap pthread_create, and then call `hpcrun_gen_thread_ctxt()` to compute the backtrace. 
Unfortunately, while calling `hpcrun_generate_backtrace_no_trampoline()`, an interrupt from perf_events occurs which then calls Linux perf_events sample-source. 
From the core dump file, it turns out that the value of `_local_td.inside_hpcrun` is zero. This means perf_events sample-source thinks the sample is not from hpcrun itself, and it continues to try to record the sample. This is bad.

**Problem 2** (consequence of problem 1):
>We know that function `hpcrun_gen_thread_ctxt()` set the value handling_sample to `0xdeadbeef`.
However, since perf_events handler continues to record the sample, it encounters that the attribute of `handling_sample` is already set to `0xdeadbeef`, thus it fails the assertion and generates a core dump.

If we fix problem 1, problem 2 won't occur. 
- Ideally, libmonitor shouldn't deliver interrupt signal inside libmonitor itself. Not sure how to fix this.
- Another solution is to set `_local_td.inside_hpcrun` to zero very early inside `hpcrun_gen_thread_ctxt()` to avoid the sample-source handler to continue to record sample.  But this is just a temporary hack.

**Symptom**:
- crashed (assertion failed) when running pyramids async type with 4 cpus on `handling_sample.c:69`
```
67      hpcrun_set_handling_sample(thread_data_t *td)
68      {
69        assert(td->handling_sample == 0);
70
71        td->handling_sample = 0xDEADBEEF;
72      }
```
- reason of assertion failure: the value of `td->handling_sample` is not zero
```
(gdb) p/x td->handling_sample
$2 = 0xdeadbeef 
```

- reason of incorrect value of ` td->handling_sample` is because we interrupt inside hpcrun and but the variable inside_hpcrun is not set yet.
```
#0  0x00007f652dc21fcb in raise () from /lib64/libpthread.so.0                                                                      
#1  0x00007f652de35388 in monitor_signal_handler (sig=6, info=<optimized out>, context=0x7f5ba12f6ec0) at ../../libmonitor/src/signal.c:264
#2  <signal handler called>

#3  0x00007f652d0675f7 in raise () from /lib64/libc.so.6
#4  0x00007f652d068ce8 in abort () from /lib64/libc.so.6
#5  0x00007f652d060566 in __assert_fail_base () from /lib64/libc.so.6
#6  0x00007f652d060612 in __assert_fail () from /lib64/libc.so.6
#7  0x00007f652e06c83d in hpcrun_set_handling_sample (td=0x7f652001a000) at ../../../../src/tool/hpcrun/handling_sample.c:69
#8  0x00007f652e06e8aa in hpcrun_sample_callpath (context=0x7f5ba12f8240, metricId=0, metricIncr=..., skipInner=0, isSync=0, data=0x7f5ba12f7ec0)
    at ../../../../src/tool/hpcrun/sample_event.c:216
#9  0x00007f652e07fb14 in record_sample (current=0x7f6195acd5d8, mmap_data=0x7f5ba12f7f50, context=0x7f5ba12f8240, sv=0x7f5ba12f8120)
    at ../../../../src/tool/hpcrun/sample-sources/perf/linux_perf.c:549
#10 0x00007f652e080c7f in perf_event_handler (sig=38, siginfo=0x7f5ba12f8370, context=0x7f5ba12f8240) at ../../../../src/tool/hpcrun/sample-sources/perf/linux_perf.c:1103
#11 0x00007f652de352c4 in monitor_signal_handler (sig=38, info=0x7f5ba12f8370, context=0x7f5ba12f8240) at ../../libmonitor/src/signal.c:218
#12 <signal handler called>

#13 0x00007f652e085056 in hpcrun_generate_backtrace_no_trampoline (bt=0x7f5ba12f9420, context=0x7f5ba12f9490, skipInner=1) at ../../../../src/tool/hpcrun/unwind/common/backtrace.c:239
#14 0x00007f652e06ee7f in hpcrun_gen_thread_ctxt (context=0x7f5ba12f9490) at ../../../../src/tool/hpcrun/sample_event.c:365
#15 0x00007f652e06a578 in monitor_thread_pre_create () at ../../../../src/tool/hpcrun/main.c:1048

#16 0x00007f652de3ec45 in pthread_create (thread=0x7f5ba12f99f0, attr=0x0, start_routine=<optimized out>, arg=<optimized out>) at ../../libmonitor/src/pthread.c:1109

#17 0x00007f652d9c0487 in std::thread::_M_start_thread(std::shared_ptr<std::thread::_Impl_base>) () from /lib64/libstdc++.so.6
#18 0x000000000040ce8f in thread<std::__future_base::_Async_state_impl<_BoundFn, <template-parameter-1-2> >::_Async_state_impl(_BoundFn&&) [with _BoundFn = std::_Bind_simple<void (*(std::launch, double (*)[2049][2049], double (*)[2049][2049], int, int, int))(std::launch, double (*)[2049][2049], double (*)[2049][2049], int, int, int)>; _Res = void]::__lambda3> (
    __f=<optimized out>, this=0x7f5ba12f99f0) at /usr/include/c++/4.8.2/thread:135
#19 _Async_state_impl (__fn=<optimized out>, this=0x7f5b40000908) at /usr/include/c++/4.8.2/future:1497
```

**Comment by laksono** [comment]
@mwkrentel do you have an idea to solve this issue ? Is it possible for libmonitor to not deliver signals within libmonitor ?

**Comment by mwkrentel** [comment]
I'll look at the code paths here.

The first question is: we've been running this for 10 years, so why
have we not seen this before?  And I think there are two new things at
play here.  (1) this benchmark creates and destroys many short-lived
threads, and (2) perf is more aggressive about sending interrupts.

So, it's likely that monitor is not the only thing that needs to be
adjusted.

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpctoolkit/-/issues/96)
